/*
Stripy Horse API

Testing SimulatorAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package stripyhorse

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Stripy-Horse/stripyhorse-go"
)

func Test_stripyhorse_SimulatorAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SimulatorAPIService ClearJobs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var printerId string

		httpRes, err := apiClient.SimulatorAPI.ClearJobs(context.Background(), printerId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimulatorAPIService CreatePrinter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SimulatorAPI.CreatePrinter(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimulatorAPIService DeletePrinter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var printerId string

		httpRes, err := apiClient.SimulatorAPI.DeletePrinter(context.Background(), printerId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimulatorAPIService GetJob", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var printerId string
		var jobId int64

		resp, httpRes, err := apiClient.SimulatorAPI.GetJob(context.Background(), printerId, jobId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimulatorAPIService GetJobLabel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var printerId string
		var jobId int64
		var index int64

		resp, httpRes, err := apiClient.SimulatorAPI.GetJobLabel(context.Background(), printerId, jobId, index).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimulatorAPIService GetPrinter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var printerId string

		resp, httpRes, err := apiClient.SimulatorAPI.GetPrinter(context.Background(), printerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimulatorAPIService ListJobs", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var printerId string

		resp, httpRes, err := apiClient.SimulatorAPI.ListJobs(context.Background(), printerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimulatorAPIService ListPrinters", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SimulatorAPI.ListPrinters(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimulatorAPIService ResetPrinter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var printerId string

		resp, httpRes, err := apiClient.SimulatorAPI.ResetPrinter(context.Background(), printerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimulatorAPIService SetPrinterFaults", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var printerId string

		resp, httpRes, err := apiClient.SimulatorAPI.SetPrinterFaults(context.Background(), printerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SimulatorAPIService UpdatePrinter", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var printerId string

		resp, httpRes, err := apiClient.SimulatorAPI.UpdatePrinter(context.Background(), printerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
