/*
Stripy Horse API

Testing ComposeAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package stripyhorse

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Stripy-Horse/stripyhorse-go"
)

func Test_stripyhorse_ComposeAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ComposeAPIService ComposeLabel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.ComposeAPI.ComposeLabel(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
