/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
)

// checks if the UpdatePrinterInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePrinterInputBody{}

// UpdatePrinterInputBody struct for UpdatePrinterInputBody
type UpdatePrinterInputBody struct {
	AccessMode *string `json:"accessMode,omitempty"`
	Anonymize *bool `json:"anonymize,omitempty"`
	Name *string `json:"name,omitempty"`
	WebhookUrl *string `json:"webhookUrl,omitempty"`
}

// NewUpdatePrinterInputBody instantiates a new UpdatePrinterInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePrinterInputBody() *UpdatePrinterInputBody {
	this := UpdatePrinterInputBody{}
	return &this
}

// NewUpdatePrinterInputBodyWithDefaults instantiates a new UpdatePrinterInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePrinterInputBodyWithDefaults() *UpdatePrinterInputBody {
	this := UpdatePrinterInputBody{}
	return &this
}

// GetAccessMode returns the AccessMode field value if set, zero value otherwise.
func (o *UpdatePrinterInputBody) GetAccessMode() string {
	if o == nil || IsNil(o.AccessMode) {
		var ret string
		return ret
	}
	return *o.AccessMode
}

// GetAccessModeOk returns a tuple with the AccessMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePrinterInputBody) GetAccessModeOk() (*string, bool) {
	if o == nil || IsNil(o.AccessMode) {
		return nil, false
	}
	return o.AccessMode, true
}

// HasAccessMode returns a boolean if a field has been set.
func (o *UpdatePrinterInputBody) HasAccessMode() bool {
	if o != nil && !IsNil(o.AccessMode) {
		return true
	}

	return false
}

// SetAccessMode gets a reference to the given string and assigns it to the AccessMode field.
func (o *UpdatePrinterInputBody) SetAccessMode(v string) {
	o.AccessMode = &v
}

// GetAnonymize returns the Anonymize field value if set, zero value otherwise.
func (o *UpdatePrinterInputBody) GetAnonymize() bool {
	if o == nil || IsNil(o.Anonymize) {
		var ret bool
		return ret
	}
	return *o.Anonymize
}

// GetAnonymizeOk returns a tuple with the Anonymize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePrinterInputBody) GetAnonymizeOk() (*bool, bool) {
	if o == nil || IsNil(o.Anonymize) {
		return nil, false
	}
	return o.Anonymize, true
}

// HasAnonymize returns a boolean if a field has been set.
func (o *UpdatePrinterInputBody) HasAnonymize() bool {
	if o != nil && !IsNil(o.Anonymize) {
		return true
	}

	return false
}

// SetAnonymize gets a reference to the given bool and assigns it to the Anonymize field.
func (o *UpdatePrinterInputBody) SetAnonymize(v bool) {
	o.Anonymize = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdatePrinterInputBody) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePrinterInputBody) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdatePrinterInputBody) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdatePrinterInputBody) SetName(v string) {
	o.Name = &v
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise.
func (o *UpdatePrinterInputBody) GetWebhookUrl() string {
	if o == nil || IsNil(o.WebhookUrl) {
		var ret string
		return ret
	}
	return *o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePrinterInputBody) GetWebhookUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookUrl) {
		return nil, false
	}
	return o.WebhookUrl, true
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *UpdatePrinterInputBody) HasWebhookUrl() bool {
	if o != nil && !IsNil(o.WebhookUrl) {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given string and assigns it to the WebhookUrl field.
func (o *UpdatePrinterInputBody) SetWebhookUrl(v string) {
	o.WebhookUrl = &v
}

func (o UpdatePrinterInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePrinterInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessMode) {
		toSerialize["accessMode"] = o.AccessMode
	}
	if !IsNil(o.Anonymize) {
		toSerialize["anonymize"] = o.Anonymize
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.WebhookUrl) {
		toSerialize["webhookUrl"] = o.WebhookUrl
	}
	return toSerialize, nil
}

type NullableUpdatePrinterInputBody struct {
	value *UpdatePrinterInputBody
	isSet bool
}

func (v NullableUpdatePrinterInputBody) Get() *UpdatePrinterInputBody {
	return v.value
}

func (v *NullableUpdatePrinterInputBody) Set(val *UpdatePrinterInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePrinterInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePrinterInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePrinterInputBody(val *UpdatePrinterInputBody) *NullableUpdatePrinterInputBody {
	return &NullableUpdatePrinterInputBody{value: val, isSet: true}
}

func (v NullableUpdatePrinterInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePrinterInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


