/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnicodeInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnicodeInputBody{}

// UnicodeInputBody struct for UnicodeInputBody
type UnicodeInputBody struct {
	Zpl string `json:"zpl"`
}

type _UnicodeInputBody UnicodeInputBody

// NewUnicodeInputBody instantiates a new UnicodeInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnicodeInputBody(zpl string) *UnicodeInputBody {
	this := UnicodeInputBody{}
	this.Zpl = zpl
	return &this
}

// NewUnicodeInputBodyWithDefaults instantiates a new UnicodeInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnicodeInputBodyWithDefaults() *UnicodeInputBody {
	this := UnicodeInputBody{}
	return &this
}

// GetZpl returns the Zpl field value
func (o *UnicodeInputBody) GetZpl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Zpl
}

// GetZplOk returns a tuple with the Zpl field value
// and a boolean to check if the value has been set.
func (o *UnicodeInputBody) GetZplOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zpl, true
}

// SetZpl sets field value
func (o *UnicodeInputBody) SetZpl(v string) {
	o.Zpl = v
}

func (o UnicodeInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnicodeInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["zpl"] = o.Zpl
	return toSerialize, nil
}

func (o *UnicodeInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"zpl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnicodeInputBody := _UnicodeInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnicodeInputBody)

	if err != nil {
		return err
	}

	*o = UnicodeInputBody(varUnicodeInputBody)

	return err
}

type NullableUnicodeInputBody struct {
	value *UnicodeInputBody
	isSet bool
}

func (v NullableUnicodeInputBody) Get() *UnicodeInputBody {
	return v.value
}

func (v *NullableUnicodeInputBody) Set(val *UnicodeInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUnicodeInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUnicodeInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnicodeInputBody(val *UnicodeInputBody) *NullableUnicodeInputBody {
	return &NullableUnicodeInputBody{value: val, isSet: true}
}

func (v NullableUnicodeInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnicodeInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


