/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RenderOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RenderOutputBody{}

// RenderOutputBody struct for RenderOutputBody
type RenderOutputBody struct {
	LabelCount int64 `json:"labelCount"`
	Labels []RenderedLabel `json:"labels"`
}

type _RenderOutputBody RenderOutputBody

// NewRenderOutputBody instantiates a new RenderOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRenderOutputBody(labelCount int64, labels []RenderedLabel) *RenderOutputBody {
	this := RenderOutputBody{}
	this.LabelCount = labelCount
	this.Labels = labels
	return &this
}

// NewRenderOutputBodyWithDefaults instantiates a new RenderOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRenderOutputBodyWithDefaults() *RenderOutputBody {
	this := RenderOutputBody{}
	return &this
}

// GetLabelCount returns the LabelCount field value
func (o *RenderOutputBody) GetLabelCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LabelCount
}

// GetLabelCountOk returns a tuple with the LabelCount field value
// and a boolean to check if the value has been set.
func (o *RenderOutputBody) GetLabelCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LabelCount, true
}

// SetLabelCount sets field value
func (o *RenderOutputBody) SetLabelCount(v int64) {
	o.LabelCount = v
}

// GetLabels returns the Labels field value
// If the value is explicit nil, the zero value for []RenderedLabel will be returned
func (o *RenderOutputBody) GetLabels() []RenderedLabel {
	if o == nil {
		var ret []RenderedLabel
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RenderOutputBody) GetLabelsOk() ([]RenderedLabel, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// SetLabels sets field value
func (o *RenderOutputBody) SetLabels(v []RenderedLabel) {
	o.Labels = v
}

func (o RenderOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RenderOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["labelCount"] = o.LabelCount
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	return toSerialize, nil
}

func (o *RenderOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"labelCount",
		"labels",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRenderOutputBody := _RenderOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRenderOutputBody)

	if err != nil {
		return err
	}

	*o = RenderOutputBody(varRenderOutputBody)

	return err
}

type NullableRenderOutputBody struct {
	value *RenderOutputBody
	isSet bool
}

func (v NullableRenderOutputBody) Get() *RenderOutputBody {
	return v.value
}

func (v *NullableRenderOutputBody) Set(val *RenderOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableRenderOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableRenderOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRenderOutputBody(val *RenderOutputBody) *NullableRenderOutputBody {
	return &NullableRenderOutputBody{value: val, isSet: true}
}

func (v NullableRenderOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRenderOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


