/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PreflightOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PreflightOutputBody{}

// PreflightOutputBody struct for PreflightOutputBody
type PreflightOutputBody struct {
	// One report per rendered label
	Labels []Report `json:"labels"`
	// Static ZPL findings: structure, encoding, bounds
	Lint []Finding `json:"lint"`
}

type _PreflightOutputBody PreflightOutputBody

// NewPreflightOutputBody instantiates a new PreflightOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreflightOutputBody(labels []Report, lint []Finding) *PreflightOutputBody {
	this := PreflightOutputBody{}
	this.Labels = labels
	this.Lint = lint
	return &this
}

// NewPreflightOutputBodyWithDefaults instantiates a new PreflightOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreflightOutputBodyWithDefaults() *PreflightOutputBody {
	this := PreflightOutputBody{}
	return &this
}

// GetLabels returns the Labels field value
// If the value is explicit nil, the zero value for []Report will be returned
func (o *PreflightOutputBody) GetLabels() []Report {
	if o == nil {
		var ret []Report
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PreflightOutputBody) GetLabelsOk() ([]Report, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// SetLabels sets field value
func (o *PreflightOutputBody) SetLabels(v []Report) {
	o.Labels = v
}

// GetLint returns the Lint field value
// If the value is explicit nil, the zero value for []Finding will be returned
func (o *PreflightOutputBody) GetLint() []Finding {
	if o == nil {
		var ret []Finding
		return ret
	}

	return o.Lint
}

// GetLintOk returns a tuple with the Lint field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PreflightOutputBody) GetLintOk() ([]Finding, bool) {
	if o == nil || IsNil(o.Lint) {
		return nil, false
	}
	return o.Lint, true
}

// SetLint sets field value
func (o *PreflightOutputBody) SetLint(v []Finding) {
	o.Lint = v
}

func (o PreflightOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PreflightOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.Lint != nil {
		toSerialize["lint"] = o.Lint
	}
	return toSerialize, nil
}

func (o *PreflightOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"labels",
		"lint",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPreflightOutputBody := _PreflightOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPreflightOutputBody)

	if err != nil {
		return err
	}

	*o = PreflightOutputBody(varPreflightOutputBody)

	return err
}

type NullablePreflightOutputBody struct {
	value *PreflightOutputBody
	isSet bool
}

func (v NullablePreflightOutputBody) Get() *PreflightOutputBody {
	return v.value
}

func (v *NullablePreflightOutputBody) Set(val *PreflightOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullablePreflightOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullablePreflightOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreflightOutputBody(val *PreflightOutputBody) *NullablePreflightOutputBody {
	return &NullablePreflightOutputBody{value: val, isSet: true}
}

func (v NullablePreflightOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreflightOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


