/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Element type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Element{}

// Element struct for Element
type Element struct {
	// Alignment when wrapping
	Align *string `json:"align,omitempty"`
	// Which corner x,y names. topLeft (^FO, default); bottomLeft (^FT: the text baseline, what most designer-exported ZPL uses); the Right variants make x the field's right edge (ZPL justification 1)
	Anchor *string `json:"anchor,omitempty"`
	// Grid columns (default 1)
	Columns *int64 `json:"columns,omitempty"`
	// Box corner rounding 0-8
	CornerRadius *int64 `json:"cornerRadius,omitempty"`
	// Barcode payload; {{name}} interpolates
	Data *string `json:"data,omitempty"`
	// Circle diameter in dots
	Diameter *int64 `json:"diameter,omitempty"`
	// QR error correction (default M)
	ErrorCorrection *string `json:"errorCorrection,omitempty"`
	// Printer font: 0 (scalable, default) or A-Z
	Font *string `json:"font,omitempty"`
	// Character height in dots (text)
	FontHeight *int64 `json:"fontHeight,omitempty"`
	// Character width in dots; 0 follows fontHeight
	FontWidth *int64 `json:"fontWidth,omitempty"`
	// Bar height in dots (1D) / box height in dots (box)
	Height *int64 `json:"height,omitempty"`
	// Line length in dots
	Length *int64 `json:"length,omitempty"`
	// Extra dots between wrapped lines
	LineSpacing *int64 `json:"lineSpacing,omitempty"`
	// Max lines when wrapping (default 1)
	Lines *int64 `json:"lines,omitempty"`
	// QR module magnification (default 3)
	Magnification *int64 `json:"magnification,omitempty"`
	// Wrap text into a block this many dots wide
	MaxWidth *int64 `json:"maxWidth,omitempty"`
	// Code 128 mode: N none (default), U UCC case, A automatic subset switching, D UCC/EAN application identifiers
	Mode *string `json:"mode,omitempty"`
	// DataMatrix module size in dots (default 4)
	ModuleSize *int64 `json:"moduleSize,omitempty"`
	// Narrow element width in dots (1D; default 3)
	ModuleWidth *int64 `json:"moduleWidth,omitempty"`
	// Line direction
	Orientation *string `json:"orientation,omitempty"`
	// PNG/GIF/JPEG, base64-encoded
	Png *string `json:"png,omitempty"`
	// Print the human-readable line under 1D barcodes (default true)
	PrintText *bool `json:"printText,omitempty"`
	Rotation *int64 `json:"rotation,omitempty"`
	// Grid rows (default 1)
	Rows *int64 `json:"rows,omitempty"`
	// Text content; {{name}} interpolates from variables
	Text *string `json:"text,omitempty"`
	// Stroke thickness in dots (default 1)
	Thickness *int64 `json:"thickness,omitempty"`
	// Bitonal threshold (default 128)
	Threshold *int64 `json:"threshold,omitempty"`
	// What to place
	Type string `json:"type"`
	// Box/image width in dots
	Width *int64 `json:"width,omitempty"`
	// Left edge in dots
	X *int64 `json:"x,omitempty"`
	// Top edge in dots
	Y *int64 `json:"y,omitempty"`
	// Verbatim ZPL commands (raw only) - the escape hatch
	Zpl *string `json:"zpl,omitempty"`
}

type _Element Element

// NewElement instantiates a new Element object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewElement(type_ string) *Element {
	this := Element{}
	this.Type = type_
	return &this
}

// NewElementWithDefaults instantiates a new Element object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewElementWithDefaults() *Element {
	this := Element{}
	return &this
}

// GetAlign returns the Align field value if set, zero value otherwise.
func (o *Element) GetAlign() string {
	if o == nil || IsNil(o.Align) {
		var ret string
		return ret
	}
	return *o.Align
}

// GetAlignOk returns a tuple with the Align field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetAlignOk() (*string, bool) {
	if o == nil || IsNil(o.Align) {
		return nil, false
	}
	return o.Align, true
}

// HasAlign returns a boolean if a field has been set.
func (o *Element) HasAlign() bool {
	if o != nil && !IsNil(o.Align) {
		return true
	}

	return false
}

// SetAlign gets a reference to the given string and assigns it to the Align field.
func (o *Element) SetAlign(v string) {
	o.Align = &v
}

// GetAnchor returns the Anchor field value if set, zero value otherwise.
func (o *Element) GetAnchor() string {
	if o == nil || IsNil(o.Anchor) {
		var ret string
		return ret
	}
	return *o.Anchor
}

// GetAnchorOk returns a tuple with the Anchor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetAnchorOk() (*string, bool) {
	if o == nil || IsNil(o.Anchor) {
		return nil, false
	}
	return o.Anchor, true
}

// HasAnchor returns a boolean if a field has been set.
func (o *Element) HasAnchor() bool {
	if o != nil && !IsNil(o.Anchor) {
		return true
	}

	return false
}

// SetAnchor gets a reference to the given string and assigns it to the Anchor field.
func (o *Element) SetAnchor(v string) {
	o.Anchor = &v
}

// GetColumns returns the Columns field value if set, zero value otherwise.
func (o *Element) GetColumns() int64 {
	if o == nil || IsNil(o.Columns) {
		var ret int64
		return ret
	}
	return *o.Columns
}

// GetColumnsOk returns a tuple with the Columns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetColumnsOk() (*int64, bool) {
	if o == nil || IsNil(o.Columns) {
		return nil, false
	}
	return o.Columns, true
}

// HasColumns returns a boolean if a field has been set.
func (o *Element) HasColumns() bool {
	if o != nil && !IsNil(o.Columns) {
		return true
	}

	return false
}

// SetColumns gets a reference to the given int64 and assigns it to the Columns field.
func (o *Element) SetColumns(v int64) {
	o.Columns = &v
}

// GetCornerRadius returns the CornerRadius field value if set, zero value otherwise.
func (o *Element) GetCornerRadius() int64 {
	if o == nil || IsNil(o.CornerRadius) {
		var ret int64
		return ret
	}
	return *o.CornerRadius
}

// GetCornerRadiusOk returns a tuple with the CornerRadius field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetCornerRadiusOk() (*int64, bool) {
	if o == nil || IsNil(o.CornerRadius) {
		return nil, false
	}
	return o.CornerRadius, true
}

// HasCornerRadius returns a boolean if a field has been set.
func (o *Element) HasCornerRadius() bool {
	if o != nil && !IsNil(o.CornerRadius) {
		return true
	}

	return false
}

// SetCornerRadius gets a reference to the given int64 and assigns it to the CornerRadius field.
func (o *Element) SetCornerRadius(v int64) {
	o.CornerRadius = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Element) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Element) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *Element) SetData(v string) {
	o.Data = &v
}

// GetDiameter returns the Diameter field value if set, zero value otherwise.
func (o *Element) GetDiameter() int64 {
	if o == nil || IsNil(o.Diameter) {
		var ret int64
		return ret
	}
	return *o.Diameter
}

// GetDiameterOk returns a tuple with the Diameter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetDiameterOk() (*int64, bool) {
	if o == nil || IsNil(o.Diameter) {
		return nil, false
	}
	return o.Diameter, true
}

// HasDiameter returns a boolean if a field has been set.
func (o *Element) HasDiameter() bool {
	if o != nil && !IsNil(o.Diameter) {
		return true
	}

	return false
}

// SetDiameter gets a reference to the given int64 and assigns it to the Diameter field.
func (o *Element) SetDiameter(v int64) {
	o.Diameter = &v
}

// GetErrorCorrection returns the ErrorCorrection field value if set, zero value otherwise.
func (o *Element) GetErrorCorrection() string {
	if o == nil || IsNil(o.ErrorCorrection) {
		var ret string
		return ret
	}
	return *o.ErrorCorrection
}

// GetErrorCorrectionOk returns a tuple with the ErrorCorrection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetErrorCorrectionOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorCorrection) {
		return nil, false
	}
	return o.ErrorCorrection, true
}

// HasErrorCorrection returns a boolean if a field has been set.
func (o *Element) HasErrorCorrection() bool {
	if o != nil && !IsNil(o.ErrorCorrection) {
		return true
	}

	return false
}

// SetErrorCorrection gets a reference to the given string and assigns it to the ErrorCorrection field.
func (o *Element) SetErrorCorrection(v string) {
	o.ErrorCorrection = &v
}

// GetFont returns the Font field value if set, zero value otherwise.
func (o *Element) GetFont() string {
	if o == nil || IsNil(o.Font) {
		var ret string
		return ret
	}
	return *o.Font
}

// GetFontOk returns a tuple with the Font field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetFontOk() (*string, bool) {
	if o == nil || IsNil(o.Font) {
		return nil, false
	}
	return o.Font, true
}

// HasFont returns a boolean if a field has been set.
func (o *Element) HasFont() bool {
	if o != nil && !IsNil(o.Font) {
		return true
	}

	return false
}

// SetFont gets a reference to the given string and assigns it to the Font field.
func (o *Element) SetFont(v string) {
	o.Font = &v
}

// GetFontHeight returns the FontHeight field value if set, zero value otherwise.
func (o *Element) GetFontHeight() int64 {
	if o == nil || IsNil(o.FontHeight) {
		var ret int64
		return ret
	}
	return *o.FontHeight
}

// GetFontHeightOk returns a tuple with the FontHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetFontHeightOk() (*int64, bool) {
	if o == nil || IsNil(o.FontHeight) {
		return nil, false
	}
	return o.FontHeight, true
}

// HasFontHeight returns a boolean if a field has been set.
func (o *Element) HasFontHeight() bool {
	if o != nil && !IsNil(o.FontHeight) {
		return true
	}

	return false
}

// SetFontHeight gets a reference to the given int64 and assigns it to the FontHeight field.
func (o *Element) SetFontHeight(v int64) {
	o.FontHeight = &v
}

// GetFontWidth returns the FontWidth field value if set, zero value otherwise.
func (o *Element) GetFontWidth() int64 {
	if o == nil || IsNil(o.FontWidth) {
		var ret int64
		return ret
	}
	return *o.FontWidth
}

// GetFontWidthOk returns a tuple with the FontWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetFontWidthOk() (*int64, bool) {
	if o == nil || IsNil(o.FontWidth) {
		return nil, false
	}
	return o.FontWidth, true
}

// HasFontWidth returns a boolean if a field has been set.
func (o *Element) HasFontWidth() bool {
	if o != nil && !IsNil(o.FontWidth) {
		return true
	}

	return false
}

// SetFontWidth gets a reference to the given int64 and assigns it to the FontWidth field.
func (o *Element) SetFontWidth(v int64) {
	o.FontWidth = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *Element) GetHeight() int64 {
	if o == nil || IsNil(o.Height) {
		var ret int64
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetHeightOk() (*int64, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *Element) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int64 and assigns it to the Height field.
func (o *Element) SetHeight(v int64) {
	o.Height = &v
}

// GetLength returns the Length field value if set, zero value otherwise.
func (o *Element) GetLength() int64 {
	if o == nil || IsNil(o.Length) {
		var ret int64
		return ret
	}
	return *o.Length
}

// GetLengthOk returns a tuple with the Length field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetLengthOk() (*int64, bool) {
	if o == nil || IsNil(o.Length) {
		return nil, false
	}
	return o.Length, true
}

// HasLength returns a boolean if a field has been set.
func (o *Element) HasLength() bool {
	if o != nil && !IsNil(o.Length) {
		return true
	}

	return false
}

// SetLength gets a reference to the given int64 and assigns it to the Length field.
func (o *Element) SetLength(v int64) {
	o.Length = &v
}

// GetLineSpacing returns the LineSpacing field value if set, zero value otherwise.
func (o *Element) GetLineSpacing() int64 {
	if o == nil || IsNil(o.LineSpacing) {
		var ret int64
		return ret
	}
	return *o.LineSpacing
}

// GetLineSpacingOk returns a tuple with the LineSpacing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetLineSpacingOk() (*int64, bool) {
	if o == nil || IsNil(o.LineSpacing) {
		return nil, false
	}
	return o.LineSpacing, true
}

// HasLineSpacing returns a boolean if a field has been set.
func (o *Element) HasLineSpacing() bool {
	if o != nil && !IsNil(o.LineSpacing) {
		return true
	}

	return false
}

// SetLineSpacing gets a reference to the given int64 and assigns it to the LineSpacing field.
func (o *Element) SetLineSpacing(v int64) {
	o.LineSpacing = &v
}

// GetLines returns the Lines field value if set, zero value otherwise.
func (o *Element) GetLines() int64 {
	if o == nil || IsNil(o.Lines) {
		var ret int64
		return ret
	}
	return *o.Lines
}

// GetLinesOk returns a tuple with the Lines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetLinesOk() (*int64, bool) {
	if o == nil || IsNil(o.Lines) {
		return nil, false
	}
	return o.Lines, true
}

// HasLines returns a boolean if a field has been set.
func (o *Element) HasLines() bool {
	if o != nil && !IsNil(o.Lines) {
		return true
	}

	return false
}

// SetLines gets a reference to the given int64 and assigns it to the Lines field.
func (o *Element) SetLines(v int64) {
	o.Lines = &v
}

// GetMagnification returns the Magnification field value if set, zero value otherwise.
func (o *Element) GetMagnification() int64 {
	if o == nil || IsNil(o.Magnification) {
		var ret int64
		return ret
	}
	return *o.Magnification
}

// GetMagnificationOk returns a tuple with the Magnification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetMagnificationOk() (*int64, bool) {
	if o == nil || IsNil(o.Magnification) {
		return nil, false
	}
	return o.Magnification, true
}

// HasMagnification returns a boolean if a field has been set.
func (o *Element) HasMagnification() bool {
	if o != nil && !IsNil(o.Magnification) {
		return true
	}

	return false
}

// SetMagnification gets a reference to the given int64 and assigns it to the Magnification field.
func (o *Element) SetMagnification(v int64) {
	o.Magnification = &v
}

// GetMaxWidth returns the MaxWidth field value if set, zero value otherwise.
func (o *Element) GetMaxWidth() int64 {
	if o == nil || IsNil(o.MaxWidth) {
		var ret int64
		return ret
	}
	return *o.MaxWidth
}

// GetMaxWidthOk returns a tuple with the MaxWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetMaxWidthOk() (*int64, bool) {
	if o == nil || IsNil(o.MaxWidth) {
		return nil, false
	}
	return o.MaxWidth, true
}

// HasMaxWidth returns a boolean if a field has been set.
func (o *Element) HasMaxWidth() bool {
	if o != nil && !IsNil(o.MaxWidth) {
		return true
	}

	return false
}

// SetMaxWidth gets a reference to the given int64 and assigns it to the MaxWidth field.
func (o *Element) SetMaxWidth(v int64) {
	o.MaxWidth = &v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *Element) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *Element) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *Element) SetMode(v string) {
	o.Mode = &v
}

// GetModuleSize returns the ModuleSize field value if set, zero value otherwise.
func (o *Element) GetModuleSize() int64 {
	if o == nil || IsNil(o.ModuleSize) {
		var ret int64
		return ret
	}
	return *o.ModuleSize
}

// GetModuleSizeOk returns a tuple with the ModuleSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetModuleSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.ModuleSize) {
		return nil, false
	}
	return o.ModuleSize, true
}

// HasModuleSize returns a boolean if a field has been set.
func (o *Element) HasModuleSize() bool {
	if o != nil && !IsNil(o.ModuleSize) {
		return true
	}

	return false
}

// SetModuleSize gets a reference to the given int64 and assigns it to the ModuleSize field.
func (o *Element) SetModuleSize(v int64) {
	o.ModuleSize = &v
}

// GetModuleWidth returns the ModuleWidth field value if set, zero value otherwise.
func (o *Element) GetModuleWidth() int64 {
	if o == nil || IsNil(o.ModuleWidth) {
		var ret int64
		return ret
	}
	return *o.ModuleWidth
}

// GetModuleWidthOk returns a tuple with the ModuleWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetModuleWidthOk() (*int64, bool) {
	if o == nil || IsNil(o.ModuleWidth) {
		return nil, false
	}
	return o.ModuleWidth, true
}

// HasModuleWidth returns a boolean if a field has been set.
func (o *Element) HasModuleWidth() bool {
	if o != nil && !IsNil(o.ModuleWidth) {
		return true
	}

	return false
}

// SetModuleWidth gets a reference to the given int64 and assigns it to the ModuleWidth field.
func (o *Element) SetModuleWidth(v int64) {
	o.ModuleWidth = &v
}

// GetOrientation returns the Orientation field value if set, zero value otherwise.
func (o *Element) GetOrientation() string {
	if o == nil || IsNil(o.Orientation) {
		var ret string
		return ret
	}
	return *o.Orientation
}

// GetOrientationOk returns a tuple with the Orientation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetOrientationOk() (*string, bool) {
	if o == nil || IsNil(o.Orientation) {
		return nil, false
	}
	return o.Orientation, true
}

// HasOrientation returns a boolean if a field has been set.
func (o *Element) HasOrientation() bool {
	if o != nil && !IsNil(o.Orientation) {
		return true
	}

	return false
}

// SetOrientation gets a reference to the given string and assigns it to the Orientation field.
func (o *Element) SetOrientation(v string) {
	o.Orientation = &v
}

// GetPng returns the Png field value if set, zero value otherwise.
func (o *Element) GetPng() string {
	if o == nil || IsNil(o.Png) {
		var ret string
		return ret
	}
	return *o.Png
}

// GetPngOk returns a tuple with the Png field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetPngOk() (*string, bool) {
	if o == nil || IsNil(o.Png) {
		return nil, false
	}
	return o.Png, true
}

// HasPng returns a boolean if a field has been set.
func (o *Element) HasPng() bool {
	if o != nil && !IsNil(o.Png) {
		return true
	}

	return false
}

// SetPng gets a reference to the given string and assigns it to the Png field.
func (o *Element) SetPng(v string) {
	o.Png = &v
}

// GetPrintText returns the PrintText field value if set, zero value otherwise.
func (o *Element) GetPrintText() bool {
	if o == nil || IsNil(o.PrintText) {
		var ret bool
		return ret
	}
	return *o.PrintText
}

// GetPrintTextOk returns a tuple with the PrintText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetPrintTextOk() (*bool, bool) {
	if o == nil || IsNil(o.PrintText) {
		return nil, false
	}
	return o.PrintText, true
}

// HasPrintText returns a boolean if a field has been set.
func (o *Element) HasPrintText() bool {
	if o != nil && !IsNil(o.PrintText) {
		return true
	}

	return false
}

// SetPrintText gets a reference to the given bool and assigns it to the PrintText field.
func (o *Element) SetPrintText(v bool) {
	o.PrintText = &v
}

// GetRotation returns the Rotation field value if set, zero value otherwise.
func (o *Element) GetRotation() int64 {
	if o == nil || IsNil(o.Rotation) {
		var ret int64
		return ret
	}
	return *o.Rotation
}

// GetRotationOk returns a tuple with the Rotation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetRotationOk() (*int64, bool) {
	if o == nil || IsNil(o.Rotation) {
		return nil, false
	}
	return o.Rotation, true
}

// HasRotation returns a boolean if a field has been set.
func (o *Element) HasRotation() bool {
	if o != nil && !IsNil(o.Rotation) {
		return true
	}

	return false
}

// SetRotation gets a reference to the given int64 and assigns it to the Rotation field.
func (o *Element) SetRotation(v int64) {
	o.Rotation = &v
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *Element) GetRows() int64 {
	if o == nil || IsNil(o.Rows) {
		var ret int64
		return ret
	}
	return *o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetRowsOk() (*int64, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *Element) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given int64 and assigns it to the Rows field.
func (o *Element) SetRows(v int64) {
	o.Rows = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *Element) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *Element) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *Element) SetText(v string) {
	o.Text = &v
}

// GetThickness returns the Thickness field value if set, zero value otherwise.
func (o *Element) GetThickness() int64 {
	if o == nil || IsNil(o.Thickness) {
		var ret int64
		return ret
	}
	return *o.Thickness
}

// GetThicknessOk returns a tuple with the Thickness field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetThicknessOk() (*int64, bool) {
	if o == nil || IsNil(o.Thickness) {
		return nil, false
	}
	return o.Thickness, true
}

// HasThickness returns a boolean if a field has been set.
func (o *Element) HasThickness() bool {
	if o != nil && !IsNil(o.Thickness) {
		return true
	}

	return false
}

// SetThickness gets a reference to the given int64 and assigns it to the Thickness field.
func (o *Element) SetThickness(v int64) {
	o.Thickness = &v
}

// GetThreshold returns the Threshold field value if set, zero value otherwise.
func (o *Element) GetThreshold() int64 {
	if o == nil || IsNil(o.Threshold) {
		var ret int64
		return ret
	}
	return *o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetThresholdOk() (*int64, bool) {
	if o == nil || IsNil(o.Threshold) {
		return nil, false
	}
	return o.Threshold, true
}

// HasThreshold returns a boolean if a field has been set.
func (o *Element) HasThreshold() bool {
	if o != nil && !IsNil(o.Threshold) {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given int64 and assigns it to the Threshold field.
func (o *Element) SetThreshold(v int64) {
	o.Threshold = &v
}

// GetType returns the Type field value
func (o *Element) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *Element) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *Element) SetType(v string) {
	o.Type = v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *Element) GetWidth() int64 {
	if o == nil || IsNil(o.Width) {
		var ret int64
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetWidthOk() (*int64, bool) {
	if o == nil || IsNil(o.Width) {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *Element) HasWidth() bool {
	if o != nil && !IsNil(o.Width) {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int64 and assigns it to the Width field.
func (o *Element) SetWidth(v int64) {
	o.Width = &v
}

// GetX returns the X field value if set, zero value otherwise.
func (o *Element) GetX() int64 {
	if o == nil || IsNil(o.X) {
		var ret int64
		return ret
	}
	return *o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetXOk() (*int64, bool) {
	if o == nil || IsNil(o.X) {
		return nil, false
	}
	return o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *Element) HasX() bool {
	if o != nil && !IsNil(o.X) {
		return true
	}

	return false
}

// SetX gets a reference to the given int64 and assigns it to the X field.
func (o *Element) SetX(v int64) {
	o.X = &v
}

// GetY returns the Y field value if set, zero value otherwise.
func (o *Element) GetY() int64 {
	if o == nil || IsNil(o.Y) {
		var ret int64
		return ret
	}
	return *o.Y
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetYOk() (*int64, bool) {
	if o == nil || IsNil(o.Y) {
		return nil, false
	}
	return o.Y, true
}

// HasY returns a boolean if a field has been set.
func (o *Element) HasY() bool {
	if o != nil && !IsNil(o.Y) {
		return true
	}

	return false
}

// SetY gets a reference to the given int64 and assigns it to the Y field.
func (o *Element) SetY(v int64) {
	o.Y = &v
}

// GetZpl returns the Zpl field value if set, zero value otherwise.
func (o *Element) GetZpl() string {
	if o == nil || IsNil(o.Zpl) {
		var ret string
		return ret
	}
	return *o.Zpl
}

// GetZplOk returns a tuple with the Zpl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Element) GetZplOk() (*string, bool) {
	if o == nil || IsNil(o.Zpl) {
		return nil, false
	}
	return o.Zpl, true
}

// HasZpl returns a boolean if a field has been set.
func (o *Element) HasZpl() bool {
	if o != nil && !IsNil(o.Zpl) {
		return true
	}

	return false
}

// SetZpl gets a reference to the given string and assigns it to the Zpl field.
func (o *Element) SetZpl(v string) {
	o.Zpl = &v
}

func (o Element) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Element) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Align) {
		toSerialize["align"] = o.Align
	}
	if !IsNil(o.Anchor) {
		toSerialize["anchor"] = o.Anchor
	}
	if !IsNil(o.Columns) {
		toSerialize["columns"] = o.Columns
	}
	if !IsNil(o.CornerRadius) {
		toSerialize["cornerRadius"] = o.CornerRadius
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Diameter) {
		toSerialize["diameter"] = o.Diameter
	}
	if !IsNil(o.ErrorCorrection) {
		toSerialize["errorCorrection"] = o.ErrorCorrection
	}
	if !IsNil(o.Font) {
		toSerialize["font"] = o.Font
	}
	if !IsNil(o.FontHeight) {
		toSerialize["fontHeight"] = o.FontHeight
	}
	if !IsNil(o.FontWidth) {
		toSerialize["fontWidth"] = o.FontWidth
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Length) {
		toSerialize["length"] = o.Length
	}
	if !IsNil(o.LineSpacing) {
		toSerialize["lineSpacing"] = o.LineSpacing
	}
	if !IsNil(o.Lines) {
		toSerialize["lines"] = o.Lines
	}
	if !IsNil(o.Magnification) {
		toSerialize["magnification"] = o.Magnification
	}
	if !IsNil(o.MaxWidth) {
		toSerialize["maxWidth"] = o.MaxWidth
	}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	if !IsNil(o.ModuleSize) {
		toSerialize["moduleSize"] = o.ModuleSize
	}
	if !IsNil(o.ModuleWidth) {
		toSerialize["moduleWidth"] = o.ModuleWidth
	}
	if !IsNil(o.Orientation) {
		toSerialize["orientation"] = o.Orientation
	}
	if !IsNil(o.Png) {
		toSerialize["png"] = o.Png
	}
	if !IsNil(o.PrintText) {
		toSerialize["printText"] = o.PrintText
	}
	if !IsNil(o.Rotation) {
		toSerialize["rotation"] = o.Rotation
	}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Thickness) {
		toSerialize["thickness"] = o.Thickness
	}
	if !IsNil(o.Threshold) {
		toSerialize["threshold"] = o.Threshold
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Width) {
		toSerialize["width"] = o.Width
	}
	if !IsNil(o.X) {
		toSerialize["x"] = o.X
	}
	if !IsNil(o.Y) {
		toSerialize["y"] = o.Y
	}
	if !IsNil(o.Zpl) {
		toSerialize["zpl"] = o.Zpl
	}
	return toSerialize, nil
}

func (o *Element) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varElement := _Element{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varElement)

	if err != nil {
		return err
	}

	*o = Element(varElement)

	return err
}

type NullableElement struct {
	value *Element
	isSet bool
}

func (v NullableElement) Get() *Element {
	return v.value
}

func (v *NullableElement) Set(val *Element) {
	v.value = val
	v.isSet = true
}

func (v NullableElement) IsSet() bool {
	return v.isSet
}

func (v *NullableElement) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableElement(val *Element) *NullableElement {
	return &NullableElement{value: val, isSet: true}
}

func (v NullableElement) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableElement) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


