/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ZplHTMLInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ZplHTMLInputBody{}

// ZplHTMLInputBody struct for ZplHTMLInputBody
type ZplHTMLInputBody struct {
	// Print density in dots/mm (152/203/300/600 dpi); default 8
	Dpmm *int64 `json:"dpmm,omitempty"`
	HeightMm *float64 `json:"heightMm,omitempty"`
	// Named label size in inches; alternative to widthMm/heightMm
	Preset *string `json:"preset,omitempty"`
	WidthMm *float64 `json:"widthMm,omitempty"`
	Zpl string `json:"zpl"`
}

type _ZplHTMLInputBody ZplHTMLInputBody

// NewZplHTMLInputBody instantiates a new ZplHTMLInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZplHTMLInputBody(zpl string) *ZplHTMLInputBody {
	this := ZplHTMLInputBody{}
	this.Zpl = zpl
	return &this
}

// NewZplHTMLInputBodyWithDefaults instantiates a new ZplHTMLInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZplHTMLInputBodyWithDefaults() *ZplHTMLInputBody {
	this := ZplHTMLInputBody{}
	return &this
}

// GetDpmm returns the Dpmm field value if set, zero value otherwise.
func (o *ZplHTMLInputBody) GetDpmm() int64 {
	if o == nil || IsNil(o.Dpmm) {
		var ret int64
		return ret
	}
	return *o.Dpmm
}

// GetDpmmOk returns a tuple with the Dpmm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZplHTMLInputBody) GetDpmmOk() (*int64, bool) {
	if o == nil || IsNil(o.Dpmm) {
		return nil, false
	}
	return o.Dpmm, true
}

// HasDpmm returns a boolean if a field has been set.
func (o *ZplHTMLInputBody) HasDpmm() bool {
	if o != nil && !IsNil(o.Dpmm) {
		return true
	}

	return false
}

// SetDpmm gets a reference to the given int64 and assigns it to the Dpmm field.
func (o *ZplHTMLInputBody) SetDpmm(v int64) {
	o.Dpmm = &v
}

// GetHeightMm returns the HeightMm field value if set, zero value otherwise.
func (o *ZplHTMLInputBody) GetHeightMm() float64 {
	if o == nil || IsNil(o.HeightMm) {
		var ret float64
		return ret
	}
	return *o.HeightMm
}

// GetHeightMmOk returns a tuple with the HeightMm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZplHTMLInputBody) GetHeightMmOk() (*float64, bool) {
	if o == nil || IsNil(o.HeightMm) {
		return nil, false
	}
	return o.HeightMm, true
}

// HasHeightMm returns a boolean if a field has been set.
func (o *ZplHTMLInputBody) HasHeightMm() bool {
	if o != nil && !IsNil(o.HeightMm) {
		return true
	}

	return false
}

// SetHeightMm gets a reference to the given float64 and assigns it to the HeightMm field.
func (o *ZplHTMLInputBody) SetHeightMm(v float64) {
	o.HeightMm = &v
}

// GetPreset returns the Preset field value if set, zero value otherwise.
func (o *ZplHTMLInputBody) GetPreset() string {
	if o == nil || IsNil(o.Preset) {
		var ret string
		return ret
	}
	return *o.Preset
}

// GetPresetOk returns a tuple with the Preset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZplHTMLInputBody) GetPresetOk() (*string, bool) {
	if o == nil || IsNil(o.Preset) {
		return nil, false
	}
	return o.Preset, true
}

// HasPreset returns a boolean if a field has been set.
func (o *ZplHTMLInputBody) HasPreset() bool {
	if o != nil && !IsNil(o.Preset) {
		return true
	}

	return false
}

// SetPreset gets a reference to the given string and assigns it to the Preset field.
func (o *ZplHTMLInputBody) SetPreset(v string) {
	o.Preset = &v
}

// GetWidthMm returns the WidthMm field value if set, zero value otherwise.
func (o *ZplHTMLInputBody) GetWidthMm() float64 {
	if o == nil || IsNil(o.WidthMm) {
		var ret float64
		return ret
	}
	return *o.WidthMm
}

// GetWidthMmOk returns a tuple with the WidthMm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ZplHTMLInputBody) GetWidthMmOk() (*float64, bool) {
	if o == nil || IsNil(o.WidthMm) {
		return nil, false
	}
	return o.WidthMm, true
}

// HasWidthMm returns a boolean if a field has been set.
func (o *ZplHTMLInputBody) HasWidthMm() bool {
	if o != nil && !IsNil(o.WidthMm) {
		return true
	}

	return false
}

// SetWidthMm gets a reference to the given float64 and assigns it to the WidthMm field.
func (o *ZplHTMLInputBody) SetWidthMm(v float64) {
	o.WidthMm = &v
}

// GetZpl returns the Zpl field value
func (o *ZplHTMLInputBody) GetZpl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Zpl
}

// GetZplOk returns a tuple with the Zpl field value
// and a boolean to check if the value has been set.
func (o *ZplHTMLInputBody) GetZplOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zpl, true
}

// SetZpl sets field value
func (o *ZplHTMLInputBody) SetZpl(v string) {
	o.Zpl = v
}

func (o ZplHTMLInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ZplHTMLInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dpmm) {
		toSerialize["dpmm"] = o.Dpmm
	}
	if !IsNil(o.HeightMm) {
		toSerialize["heightMm"] = o.HeightMm
	}
	if !IsNil(o.Preset) {
		toSerialize["preset"] = o.Preset
	}
	if !IsNil(o.WidthMm) {
		toSerialize["widthMm"] = o.WidthMm
	}
	toSerialize["zpl"] = o.Zpl
	return toSerialize, nil
}

func (o *ZplHTMLInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"zpl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varZplHTMLInputBody := _ZplHTMLInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varZplHTMLInputBody)

	if err != nil {
		return err
	}

	*o = ZplHTMLInputBody(varZplHTMLInputBody)

	return err
}

type NullableZplHTMLInputBody struct {
	value *ZplHTMLInputBody
	isSet bool
}

func (v NullableZplHTMLInputBody) Get() *ZplHTMLInputBody {
	return v.value
}

func (v *NullableZplHTMLInputBody) Set(val *ZplHTMLInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableZplHTMLInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableZplHTMLInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZplHTMLInputBody(val *ZplHTMLInputBody) *NullableZplHTMLInputBody {
	return &NullableZplHTMLInputBody{value: val, isSet: true}
}

func (v NullableZplHTMLInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZplHTMLInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


