/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListJobsOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListJobsOutputBody{}

// ListJobsOutputBody struct for ListJobsOutputBody
type ListJobsOutputBody struct {
	Jobs []JobSummary `json:"jobs"`
}

type _ListJobsOutputBody ListJobsOutputBody

// NewListJobsOutputBody instantiates a new ListJobsOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListJobsOutputBody(jobs []JobSummary) *ListJobsOutputBody {
	this := ListJobsOutputBody{}
	this.Jobs = jobs
	return &this
}

// NewListJobsOutputBodyWithDefaults instantiates a new ListJobsOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListJobsOutputBodyWithDefaults() *ListJobsOutputBody {
	this := ListJobsOutputBody{}
	return &this
}

// GetJobs returns the Jobs field value
// If the value is explicit nil, the zero value for []JobSummary will be returned
func (o *ListJobsOutputBody) GetJobs() []JobSummary {
	if o == nil {
		var ret []JobSummary
		return ret
	}

	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListJobsOutputBody) GetJobsOk() ([]JobSummary, bool) {
	if o == nil || IsNil(o.Jobs) {
		return nil, false
	}
	return o.Jobs, true
}

// SetJobs sets field value
func (o *ListJobsOutputBody) SetJobs(v []JobSummary) {
	o.Jobs = v
}

func (o ListJobsOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListJobsOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Jobs != nil {
		toSerialize["jobs"] = o.Jobs
	}
	return toSerialize, nil
}

func (o *ListJobsOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListJobsOutputBody := _ListJobsOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListJobsOutputBody)

	if err != nil {
		return err
	}

	*o = ListJobsOutputBody(varListJobsOutputBody)

	return err
}

type NullableListJobsOutputBody struct {
	value *ListJobsOutputBody
	isSet bool
}

func (v NullableListJobsOutputBody) Get() *ListJobsOutputBody {
	return v.value
}

func (v *NullableListJobsOutputBody) Set(val *ListJobsOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableListJobsOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableListJobsOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListJobsOutputBody(val *ListJobsOutputBody) *NullableListJobsOutputBody {
	return &NullableListJobsOutputBody{value: val, isSet: true}
}

func (v NullableListJobsOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListJobsOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


