/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the HeldJob type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HeldJob{}

// HeldJob struct for HeldJob
type HeldJob struct {
	// Size of the held frame
	Bytes int64 `json:"bytes"`
	ReceivedAt time.Time `json:"receivedAt"`
	// How it arrived: tcp or https
	Source string `json:"source"`
}

type _HeldJob HeldJob

// NewHeldJob instantiates a new HeldJob object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHeldJob(bytes int64, receivedAt time.Time, source string) *HeldJob {
	this := HeldJob{}
	this.Bytes = bytes
	this.ReceivedAt = receivedAt
	this.Source = source
	return &this
}

// NewHeldJobWithDefaults instantiates a new HeldJob object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHeldJobWithDefaults() *HeldJob {
	this := HeldJob{}
	return &this
}

// GetBytes returns the Bytes field value
func (o *HeldJob) GetBytes() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Bytes
}

// GetBytesOk returns a tuple with the Bytes field value
// and a boolean to check if the value has been set.
func (o *HeldJob) GetBytesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bytes, true
}

// SetBytes sets field value
func (o *HeldJob) SetBytes(v int64) {
	o.Bytes = v
}

// GetReceivedAt returns the ReceivedAt field value
func (o *HeldJob) GetReceivedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ReceivedAt
}

// GetReceivedAtOk returns a tuple with the ReceivedAt field value
// and a boolean to check if the value has been set.
func (o *HeldJob) GetReceivedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceivedAt, true
}

// SetReceivedAt sets field value
func (o *HeldJob) SetReceivedAt(v time.Time) {
	o.ReceivedAt = v
}

// GetSource returns the Source field value
func (o *HeldJob) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *HeldJob) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *HeldJob) SetSource(v string) {
	o.Source = v
}

func (o HeldJob) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HeldJob) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bytes"] = o.Bytes
	toSerialize["receivedAt"] = o.ReceivedAt
	toSerialize["source"] = o.Source
	return toSerialize, nil
}

func (o *HeldJob) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bytes",
		"receivedAt",
		"source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHeldJob := _HeldJob{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHeldJob)

	if err != nil {
		return err
	}

	*o = HeldJob(varHeldJob)

	return err
}

type NullableHeldJob struct {
	value *HeldJob
	isSet bool
}

func (v NullableHeldJob) Get() *HeldJob {
	return v.value
}

func (v *NullableHeldJob) Set(val *HeldJob) {
	v.value = val
	v.isSet = true
}

func (v NullableHeldJob) IsSet() bool {
	return v.isSet
}

func (v *NullableHeldJob) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHeldJob(val *HeldJob) *NullableHeldJob {
	return &NullableHeldJob{value: val, isSet: true}
}

func (v NullableHeldJob) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHeldJob) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


