/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HostStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostStatus{}

// HostStatus struct for HostStatus
type HostStatus struct {
	// True when any condition stops printing
	Blocking bool `json:"blocking"`
	BufferFull bool `json:"bufferFull"`
	// Raw communication-settings code
	CommSettings string `json:"commSettings"`
	CorruptRam bool `json:"corruptRam"`
	DiagnosticMode bool `json:"diagnosticMode"`
	// Jobs waiting in the receive buffer
	FormatsInBuffer int64 `json:"formatsInBuffer"`
	// Raw function-settings code
	FunctionSettings string `json:"functionSettings"`
	GraphicsStored int64 `json:"graphicsStored"`
	HeadUp bool `json:"headUp"`
	LabelLengthDots int64 `json:"labelLengthDots"`
	LabelsRemaining int64 `json:"labelsRemaining"`
	OverTemp bool `json:"overTemp"`
	PaperOut bool `json:"paperOut"`
	PartialFormat bool `json:"partialFormat"`
	Password string `json:"password"`
	Paused bool `json:"paused"`
	// rewind, peel-off, tear-off, cutter or applicator
	PrintMode string `json:"printMode"`
	RibbonOut bool `json:"ribbonOut"`
	StaticRam bool `json:"staticRam"`
	ThermalTransfer bool `json:"thermalTransfer"`
	UnderTemp bool `json:"underTemp"`
}

type _HostStatus HostStatus

// NewHostStatus instantiates a new HostStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostStatus(blocking bool, bufferFull bool, commSettings string, corruptRam bool, diagnosticMode bool, formatsInBuffer int64, functionSettings string, graphicsStored int64, headUp bool, labelLengthDots int64, labelsRemaining int64, overTemp bool, paperOut bool, partialFormat bool, password string, paused bool, printMode string, ribbonOut bool, staticRam bool, thermalTransfer bool, underTemp bool) *HostStatus {
	this := HostStatus{}
	this.Blocking = blocking
	this.BufferFull = bufferFull
	this.CommSettings = commSettings
	this.CorruptRam = corruptRam
	this.DiagnosticMode = diagnosticMode
	this.FormatsInBuffer = formatsInBuffer
	this.FunctionSettings = functionSettings
	this.GraphicsStored = graphicsStored
	this.HeadUp = headUp
	this.LabelLengthDots = labelLengthDots
	this.LabelsRemaining = labelsRemaining
	this.OverTemp = overTemp
	this.PaperOut = paperOut
	this.PartialFormat = partialFormat
	this.Password = password
	this.Paused = paused
	this.PrintMode = printMode
	this.RibbonOut = ribbonOut
	this.StaticRam = staticRam
	this.ThermalTransfer = thermalTransfer
	this.UnderTemp = underTemp
	return &this
}

// NewHostStatusWithDefaults instantiates a new HostStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostStatusWithDefaults() *HostStatus {
	this := HostStatus{}
	return &this
}

// GetBlocking returns the Blocking field value
func (o *HostStatus) GetBlocking() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Blocking
}

// GetBlockingOk returns a tuple with the Blocking field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetBlockingOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Blocking, true
}

// SetBlocking sets field value
func (o *HostStatus) SetBlocking(v bool) {
	o.Blocking = v
}

// GetBufferFull returns the BufferFull field value
func (o *HostStatus) GetBufferFull() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.BufferFull
}

// GetBufferFullOk returns a tuple with the BufferFull field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetBufferFullOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BufferFull, true
}

// SetBufferFull sets field value
func (o *HostStatus) SetBufferFull(v bool) {
	o.BufferFull = v
}

// GetCommSettings returns the CommSettings field value
func (o *HostStatus) GetCommSettings() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CommSettings
}

// GetCommSettingsOk returns a tuple with the CommSettings field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetCommSettingsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommSettings, true
}

// SetCommSettings sets field value
func (o *HostStatus) SetCommSettings(v string) {
	o.CommSettings = v
}

// GetCorruptRam returns the CorruptRam field value
func (o *HostStatus) GetCorruptRam() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CorruptRam
}

// GetCorruptRamOk returns a tuple with the CorruptRam field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetCorruptRamOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CorruptRam, true
}

// SetCorruptRam sets field value
func (o *HostStatus) SetCorruptRam(v bool) {
	o.CorruptRam = v
}

// GetDiagnosticMode returns the DiagnosticMode field value
func (o *HostStatus) GetDiagnosticMode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.DiagnosticMode
}

// GetDiagnosticModeOk returns a tuple with the DiagnosticMode field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetDiagnosticModeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DiagnosticMode, true
}

// SetDiagnosticMode sets field value
func (o *HostStatus) SetDiagnosticMode(v bool) {
	o.DiagnosticMode = v
}

// GetFormatsInBuffer returns the FormatsInBuffer field value
func (o *HostStatus) GetFormatsInBuffer() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FormatsInBuffer
}

// GetFormatsInBufferOk returns a tuple with the FormatsInBuffer field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetFormatsInBufferOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FormatsInBuffer, true
}

// SetFormatsInBuffer sets field value
func (o *HostStatus) SetFormatsInBuffer(v int64) {
	o.FormatsInBuffer = v
}

// GetFunctionSettings returns the FunctionSettings field value
func (o *HostStatus) GetFunctionSettings() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FunctionSettings
}

// GetFunctionSettingsOk returns a tuple with the FunctionSettings field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetFunctionSettingsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FunctionSettings, true
}

// SetFunctionSettings sets field value
func (o *HostStatus) SetFunctionSettings(v string) {
	o.FunctionSettings = v
}

// GetGraphicsStored returns the GraphicsStored field value
func (o *HostStatus) GetGraphicsStored() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.GraphicsStored
}

// GetGraphicsStoredOk returns a tuple with the GraphicsStored field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetGraphicsStoredOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GraphicsStored, true
}

// SetGraphicsStored sets field value
func (o *HostStatus) SetGraphicsStored(v int64) {
	o.GraphicsStored = v
}

// GetHeadUp returns the HeadUp field value
func (o *HostStatus) GetHeadUp() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HeadUp
}

// GetHeadUpOk returns a tuple with the HeadUp field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetHeadUpOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HeadUp, true
}

// SetHeadUp sets field value
func (o *HostStatus) SetHeadUp(v bool) {
	o.HeadUp = v
}

// GetLabelLengthDots returns the LabelLengthDots field value
func (o *HostStatus) GetLabelLengthDots() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LabelLengthDots
}

// GetLabelLengthDotsOk returns a tuple with the LabelLengthDots field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetLabelLengthDotsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LabelLengthDots, true
}

// SetLabelLengthDots sets field value
func (o *HostStatus) SetLabelLengthDots(v int64) {
	o.LabelLengthDots = v
}

// GetLabelsRemaining returns the LabelsRemaining field value
func (o *HostStatus) GetLabelsRemaining() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LabelsRemaining
}

// GetLabelsRemainingOk returns a tuple with the LabelsRemaining field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetLabelsRemainingOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LabelsRemaining, true
}

// SetLabelsRemaining sets field value
func (o *HostStatus) SetLabelsRemaining(v int64) {
	o.LabelsRemaining = v
}

// GetOverTemp returns the OverTemp field value
func (o *HostStatus) GetOverTemp() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OverTemp
}

// GetOverTempOk returns a tuple with the OverTemp field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetOverTempOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OverTemp, true
}

// SetOverTemp sets field value
func (o *HostStatus) SetOverTemp(v bool) {
	o.OverTemp = v
}

// GetPaperOut returns the PaperOut field value
func (o *HostStatus) GetPaperOut() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PaperOut
}

// GetPaperOutOk returns a tuple with the PaperOut field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetPaperOutOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PaperOut, true
}

// SetPaperOut sets field value
func (o *HostStatus) SetPaperOut(v bool) {
	o.PaperOut = v
}

// GetPartialFormat returns the PartialFormat field value
func (o *HostStatus) GetPartialFormat() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PartialFormat
}

// GetPartialFormatOk returns a tuple with the PartialFormat field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetPartialFormatOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartialFormat, true
}

// SetPartialFormat sets field value
func (o *HostStatus) SetPartialFormat(v bool) {
	o.PartialFormat = v
}

// GetPassword returns the Password field value
func (o *HostStatus) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *HostStatus) SetPassword(v string) {
	o.Password = v
}

// GetPaused returns the Paused field value
func (o *HostStatus) GetPaused() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Paused
}

// GetPausedOk returns a tuple with the Paused field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetPausedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Paused, true
}

// SetPaused sets field value
func (o *HostStatus) SetPaused(v bool) {
	o.Paused = v
}

// GetPrintMode returns the PrintMode field value
func (o *HostStatus) GetPrintMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrintMode
}

// GetPrintModeOk returns a tuple with the PrintMode field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetPrintModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrintMode, true
}

// SetPrintMode sets field value
func (o *HostStatus) SetPrintMode(v string) {
	o.PrintMode = v
}

// GetRibbonOut returns the RibbonOut field value
func (o *HostStatus) GetRibbonOut() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RibbonOut
}

// GetRibbonOutOk returns a tuple with the RibbonOut field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetRibbonOutOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RibbonOut, true
}

// SetRibbonOut sets field value
func (o *HostStatus) SetRibbonOut(v bool) {
	o.RibbonOut = v
}

// GetStaticRam returns the StaticRam field value
func (o *HostStatus) GetStaticRam() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.StaticRam
}

// GetStaticRamOk returns a tuple with the StaticRam field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetStaticRamOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StaticRam, true
}

// SetStaticRam sets field value
func (o *HostStatus) SetStaticRam(v bool) {
	o.StaticRam = v
}

// GetThermalTransfer returns the ThermalTransfer field value
func (o *HostStatus) GetThermalTransfer() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ThermalTransfer
}

// GetThermalTransferOk returns a tuple with the ThermalTransfer field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetThermalTransferOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThermalTransfer, true
}

// SetThermalTransfer sets field value
func (o *HostStatus) SetThermalTransfer(v bool) {
	o.ThermalTransfer = v
}

// GetUnderTemp returns the UnderTemp field value
func (o *HostStatus) GetUnderTemp() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.UnderTemp
}

// GetUnderTempOk returns a tuple with the UnderTemp field value
// and a boolean to check if the value has been set.
func (o *HostStatus) GetUnderTempOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnderTemp, true
}

// SetUnderTemp sets field value
func (o *HostStatus) SetUnderTemp(v bool) {
	o.UnderTemp = v
}

func (o HostStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["blocking"] = o.Blocking
	toSerialize["bufferFull"] = o.BufferFull
	toSerialize["commSettings"] = o.CommSettings
	toSerialize["corruptRam"] = o.CorruptRam
	toSerialize["diagnosticMode"] = o.DiagnosticMode
	toSerialize["formatsInBuffer"] = o.FormatsInBuffer
	toSerialize["functionSettings"] = o.FunctionSettings
	toSerialize["graphicsStored"] = o.GraphicsStored
	toSerialize["headUp"] = o.HeadUp
	toSerialize["labelLengthDots"] = o.LabelLengthDots
	toSerialize["labelsRemaining"] = o.LabelsRemaining
	toSerialize["overTemp"] = o.OverTemp
	toSerialize["paperOut"] = o.PaperOut
	toSerialize["partialFormat"] = o.PartialFormat
	toSerialize["password"] = o.Password
	toSerialize["paused"] = o.Paused
	toSerialize["printMode"] = o.PrintMode
	toSerialize["ribbonOut"] = o.RibbonOut
	toSerialize["staticRam"] = o.StaticRam
	toSerialize["thermalTransfer"] = o.ThermalTransfer
	toSerialize["underTemp"] = o.UnderTemp
	return toSerialize, nil
}

func (o *HostStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"blocking",
		"bufferFull",
		"commSettings",
		"corruptRam",
		"diagnosticMode",
		"formatsInBuffer",
		"functionSettings",
		"graphicsStored",
		"headUp",
		"labelLengthDots",
		"labelsRemaining",
		"overTemp",
		"paperOut",
		"partialFormat",
		"password",
		"paused",
		"printMode",
		"ribbonOut",
		"staticRam",
		"thermalTransfer",
		"underTemp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostStatus := _HostStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostStatus)

	if err != nil {
		return err
	}

	*o = HostStatus(varHostStatus)

	return err
}

type NullableHostStatus struct {
	value *HostStatus
	isSet bool
}

func (v NullableHostStatus) Get() *HostStatus {
	return v.value
}

func (v *NullableHostStatus) Set(val *HostStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableHostStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableHostStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostStatus(val *HostStatus) *NullableHostStatus {
	return &NullableHostStatus{value: val, isSet: true}
}

func (v NullableHostStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


