/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ZplHTMLOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ZplHTMLOutputBody{}

// ZplHTMLOutputBody struct for ZplHTMLOutputBody
type ZplHTMLOutputBody struct {
	// Editable HTML in the convertHtml dialect
	Html string `json:"html"`
}

type _ZplHTMLOutputBody ZplHTMLOutputBody

// NewZplHTMLOutputBody instantiates a new ZplHTMLOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewZplHTMLOutputBody(html string) *ZplHTMLOutputBody {
	this := ZplHTMLOutputBody{}
	this.Html = html
	return &this
}

// NewZplHTMLOutputBodyWithDefaults instantiates a new ZplHTMLOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewZplHTMLOutputBodyWithDefaults() *ZplHTMLOutputBody {
	this := ZplHTMLOutputBody{}
	return &this
}

// GetHtml returns the Html field value
func (o *ZplHTMLOutputBody) GetHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Html
}

// GetHtmlOk returns a tuple with the Html field value
// and a boolean to check if the value has been set.
func (o *ZplHTMLOutputBody) GetHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Html, true
}

// SetHtml sets field value
func (o *ZplHTMLOutputBody) SetHtml(v string) {
	o.Html = v
}

func (o ZplHTMLOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ZplHTMLOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["html"] = o.Html
	return toSerialize, nil
}

func (o *ZplHTMLOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"html",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varZplHTMLOutputBody := _ZplHTMLOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varZplHTMLOutputBody)

	if err != nil {
		return err
	}

	*o = ZplHTMLOutputBody(varZplHTMLOutputBody)

	return err
}

type NullableZplHTMLOutputBody struct {
	value *ZplHTMLOutputBody
	isSet bool
}

func (v NullableZplHTMLOutputBody) Get() *ZplHTMLOutputBody {
	return v.value
}

func (v *NullableZplHTMLOutputBody) Set(val *ZplHTMLOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableZplHTMLOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableZplHTMLOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableZplHTMLOutputBody(val *ZplHTMLOutputBody) *NullableZplHTMLOutputBody {
	return &NullableZplHTMLOutputBody{value: val, isSet: true}
}

func (v NullableZplHTMLOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableZplHTMLOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


