/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DPIVerdict type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DPIVerdict{}

// DPIVerdict struct for DPIVerdict
type DPIVerdict struct {
	Dpmm int64 `json:"dpmm"`
	Ok bool `json:"ok"`
	XDimensionMm float64 `json:"xDimensionMm"`
}

type _DPIVerdict DPIVerdict

// NewDPIVerdict instantiates a new DPIVerdict object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDPIVerdict(dpmm int64, ok bool, xDimensionMm float64) *DPIVerdict {
	this := DPIVerdict{}
	this.Dpmm = dpmm
	this.Ok = ok
	this.XDimensionMm = xDimensionMm
	return &this
}

// NewDPIVerdictWithDefaults instantiates a new DPIVerdict object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDPIVerdictWithDefaults() *DPIVerdict {
	this := DPIVerdict{}
	return &this
}

// GetDpmm returns the Dpmm field value
func (o *DPIVerdict) GetDpmm() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Dpmm
}

// GetDpmmOk returns a tuple with the Dpmm field value
// and a boolean to check if the value has been set.
func (o *DPIVerdict) GetDpmmOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dpmm, true
}

// SetDpmm sets field value
func (o *DPIVerdict) SetDpmm(v int64) {
	o.Dpmm = v
}

// GetOk returns the Ok field value
func (o *DPIVerdict) GetOk() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Ok
}

// GetOkOk returns a tuple with the Ok field value
// and a boolean to check if the value has been set.
func (o *DPIVerdict) GetOkOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ok, true
}

// SetOk sets field value
func (o *DPIVerdict) SetOk(v bool) {
	o.Ok = v
}

// GetXDimensionMm returns the XDimensionMm field value
func (o *DPIVerdict) GetXDimensionMm() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.XDimensionMm
}

// GetXDimensionMmOk returns a tuple with the XDimensionMm field value
// and a boolean to check if the value has been set.
func (o *DPIVerdict) GetXDimensionMmOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.XDimensionMm, true
}

// SetXDimensionMm sets field value
func (o *DPIVerdict) SetXDimensionMm(v float64) {
	o.XDimensionMm = v
}

func (o DPIVerdict) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DPIVerdict) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dpmm"] = o.Dpmm
	toSerialize["ok"] = o.Ok
	toSerialize["xDimensionMm"] = o.XDimensionMm
	return toSerialize, nil
}

func (o *DPIVerdict) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dpmm",
		"ok",
		"xDimensionMm",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDPIVerdict := _DPIVerdict{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDPIVerdict)

	if err != nil {
		return err
	}

	*o = DPIVerdict(varDPIVerdict)

	return err
}

type NullableDPIVerdict struct {
	value *DPIVerdict
	isSet bool
}

func (v NullableDPIVerdict) Get() *DPIVerdict {
	return v.value
}

func (v *NullableDPIVerdict) Set(val *DPIVerdict) {
	v.value = val
	v.isSet = true
}

func (v NullableDPIVerdict) IsSet() bool {
	return v.isSet
}

func (v *NullableDPIVerdict) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDPIVerdict(val *DPIVerdict) *NullableDPIVerdict {
	return &NullableDPIVerdict{value: val, isSet: true}
}

func (v NullableDPIVerdict) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDPIVerdict) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


