/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PrinterBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrinterBody{}

// PrinterBody struct for PrinterBody
type PrinterBody struct {
	// Who may print to the TCP port: open (anyone), token (the stream must open with ~SH plus the ingest token), ip (only addresses the org has claimed)
	AccessMode string `json:"accessMode"`
	// When true, PII is masked and graphics stripped from every captured frame
	Anonymize bool `json:"anonymize"`
	CreatedAt time.Time `json:"createdAt"`
	Dpmm int64 `json:"dpmm"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	HeightMm float64 `json:"heightMm"`
	Id string `json:"id"`
	// HTTPS print capability URL. Only returned on creation.
	IngestUrl *string `json:"ingestUrl,omitempty"`
	Mode string `json:"mode"`
	Name string `json:"name"`
	State *StatusSnapshot `json:"state,omitempty"`
	Tcp PrinterBodyTCPStruct `json:"tcp"`
	// HMAC-SHA256 key for X-Stripy-Horse-Signature. Only returned on creation.
	WebhookSecret *string `json:"webhookSecret,omitempty"`
	WebhookUrl *string `json:"webhookUrl,omitempty"`
	WidthMm float64 `json:"widthMm"`
}

type _PrinterBody PrinterBody

// NewPrinterBody instantiates a new PrinterBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrinterBody(accessMode string, anonymize bool, createdAt time.Time, dpmm int64, heightMm float64, id string, mode string, name string, tcp PrinterBodyTCPStruct, widthMm float64) *PrinterBody {
	this := PrinterBody{}
	this.AccessMode = accessMode
	this.Anonymize = anonymize
	this.CreatedAt = createdAt
	this.Dpmm = dpmm
	this.HeightMm = heightMm
	this.Id = id
	this.Mode = mode
	this.Name = name
	this.Tcp = tcp
	this.WidthMm = widthMm
	return &this
}

// NewPrinterBodyWithDefaults instantiates a new PrinterBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrinterBodyWithDefaults() *PrinterBody {
	this := PrinterBody{}
	return &this
}

// GetAccessMode returns the AccessMode field value
func (o *PrinterBody) GetAccessMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessMode
}

// GetAccessModeOk returns a tuple with the AccessMode field value
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetAccessModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessMode, true
}

// SetAccessMode sets field value
func (o *PrinterBody) SetAccessMode(v string) {
	o.AccessMode = v
}

// GetAnonymize returns the Anonymize field value
func (o *PrinterBody) GetAnonymize() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Anonymize
}

// GetAnonymizeOk returns a tuple with the Anonymize field value
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetAnonymizeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Anonymize, true
}

// SetAnonymize sets field value
func (o *PrinterBody) SetAnonymize(v bool) {
	o.Anonymize = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PrinterBody) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PrinterBody) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDpmm returns the Dpmm field value
func (o *PrinterBody) GetDpmm() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Dpmm
}

// GetDpmmOk returns a tuple with the Dpmm field value
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetDpmmOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dpmm, true
}

// SetDpmm sets field value
func (o *PrinterBody) SetDpmm(v int64) {
	o.Dpmm = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *PrinterBody) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *PrinterBody) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given time.Time and assigns it to the ExpiresAt field.
func (o *PrinterBody) SetExpiresAt(v time.Time) {
	o.ExpiresAt = &v
}

// GetHeightMm returns the HeightMm field value
func (o *PrinterBody) GetHeightMm() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.HeightMm
}

// GetHeightMmOk returns a tuple with the HeightMm field value
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetHeightMmOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HeightMm, true
}

// SetHeightMm sets field value
func (o *PrinterBody) SetHeightMm(v float64) {
	o.HeightMm = v
}

// GetId returns the Id field value
func (o *PrinterBody) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PrinterBody) SetId(v string) {
	o.Id = v
}

// GetIngestUrl returns the IngestUrl field value if set, zero value otherwise.
func (o *PrinterBody) GetIngestUrl() string {
	if o == nil || IsNil(o.IngestUrl) {
		var ret string
		return ret
	}
	return *o.IngestUrl
}

// GetIngestUrlOk returns a tuple with the IngestUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetIngestUrlOk() (*string, bool) {
	if o == nil || IsNil(o.IngestUrl) {
		return nil, false
	}
	return o.IngestUrl, true
}

// HasIngestUrl returns a boolean if a field has been set.
func (o *PrinterBody) HasIngestUrl() bool {
	if o != nil && !IsNil(o.IngestUrl) {
		return true
	}

	return false
}

// SetIngestUrl gets a reference to the given string and assigns it to the IngestUrl field.
func (o *PrinterBody) SetIngestUrl(v string) {
	o.IngestUrl = &v
}

// GetMode returns the Mode field value
func (o *PrinterBody) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *PrinterBody) SetMode(v string) {
	o.Mode = v
}

// GetName returns the Name field value
func (o *PrinterBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PrinterBody) SetName(v string) {
	o.Name = v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *PrinterBody) GetState() StatusSnapshot {
	if o == nil || IsNil(o.State) {
		var ret StatusSnapshot
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetStateOk() (*StatusSnapshot, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *PrinterBody) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given StatusSnapshot and assigns it to the State field.
func (o *PrinterBody) SetState(v StatusSnapshot) {
	o.State = &v
}

// GetTcp returns the Tcp field value
func (o *PrinterBody) GetTcp() PrinterBodyTCPStruct {
	if o == nil {
		var ret PrinterBodyTCPStruct
		return ret
	}

	return o.Tcp
}

// GetTcpOk returns a tuple with the Tcp field value
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetTcpOk() (*PrinterBodyTCPStruct, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tcp, true
}

// SetTcp sets field value
func (o *PrinterBody) SetTcp(v PrinterBodyTCPStruct) {
	o.Tcp = v
}

// GetWebhookSecret returns the WebhookSecret field value if set, zero value otherwise.
func (o *PrinterBody) GetWebhookSecret() string {
	if o == nil || IsNil(o.WebhookSecret) {
		var ret string
		return ret
	}
	return *o.WebhookSecret
}

// GetWebhookSecretOk returns a tuple with the WebhookSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetWebhookSecretOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookSecret) {
		return nil, false
	}
	return o.WebhookSecret, true
}

// HasWebhookSecret returns a boolean if a field has been set.
func (o *PrinterBody) HasWebhookSecret() bool {
	if o != nil && !IsNil(o.WebhookSecret) {
		return true
	}

	return false
}

// SetWebhookSecret gets a reference to the given string and assigns it to the WebhookSecret field.
func (o *PrinterBody) SetWebhookSecret(v string) {
	o.WebhookSecret = &v
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise.
func (o *PrinterBody) GetWebhookUrl() string {
	if o == nil || IsNil(o.WebhookUrl) {
		var ret string
		return ret
	}
	return *o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetWebhookUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookUrl) {
		return nil, false
	}
	return o.WebhookUrl, true
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *PrinterBody) HasWebhookUrl() bool {
	if o != nil && !IsNil(o.WebhookUrl) {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given string and assigns it to the WebhookUrl field.
func (o *PrinterBody) SetWebhookUrl(v string) {
	o.WebhookUrl = &v
}

// GetWidthMm returns the WidthMm field value
func (o *PrinterBody) GetWidthMm() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.WidthMm
}

// GetWidthMmOk returns a tuple with the WidthMm field value
// and a boolean to check if the value has been set.
func (o *PrinterBody) GetWidthMmOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WidthMm, true
}

// SetWidthMm sets field value
func (o *PrinterBody) SetWidthMm(v float64) {
	o.WidthMm = v
}

func (o PrinterBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrinterBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accessMode"] = o.AccessMode
	toSerialize["anonymize"] = o.Anonymize
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["dpmm"] = o.Dpmm
	if !IsNil(o.ExpiresAt) {
		toSerialize["expiresAt"] = o.ExpiresAt
	}
	toSerialize["heightMm"] = o.HeightMm
	toSerialize["id"] = o.Id
	if !IsNil(o.IngestUrl) {
		toSerialize["ingestUrl"] = o.IngestUrl
	}
	toSerialize["mode"] = o.Mode
	toSerialize["name"] = o.Name
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	toSerialize["tcp"] = o.Tcp
	if !IsNil(o.WebhookSecret) {
		toSerialize["webhookSecret"] = o.WebhookSecret
	}
	if !IsNil(o.WebhookUrl) {
		toSerialize["webhookUrl"] = o.WebhookUrl
	}
	toSerialize["widthMm"] = o.WidthMm
	return toSerialize, nil
}

func (o *PrinterBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accessMode",
		"anonymize",
		"createdAt",
		"dpmm",
		"heightMm",
		"id",
		"mode",
		"name",
		"tcp",
		"widthMm",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrinterBody := _PrinterBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPrinterBody)

	if err != nil {
		return err
	}

	*o = PrinterBody(varPrinterBody)

	return err
}

type NullablePrinterBody struct {
	value *PrinterBody
	isSet bool
}

func (v NullablePrinterBody) Get() *PrinterBody {
	return v.value
}

func (v *NullablePrinterBody) Set(val *PrinterBody) {
	v.value = val
	v.isSet = true
}

func (v NullablePrinterBody) IsSet() bool {
	return v.isSet
}

func (v *NullablePrinterBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrinterBody(val *PrinterBody) *NullablePrinterBody {
	return &NullablePrinterBody{value: val, isSet: true}
}

func (v NullablePrinterBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrinterBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


