/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
)

// checks if the MediaInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MediaInputBody{}

// MediaInputBody struct for MediaInputBody
type MediaInputBody struct {
	// Labels on the roll; 0 for an endless roll
	Labels *int64 `json:"labels,omitempty"`
	// Ribbon on the spool in metres; 0 for endless, which is also what direct thermal looks like
	RibbonMetres *float64 `json:"ribbonMetres,omitempty"`
}

// NewMediaInputBody instantiates a new MediaInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMediaInputBody() *MediaInputBody {
	this := MediaInputBody{}
	return &this
}

// NewMediaInputBodyWithDefaults instantiates a new MediaInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMediaInputBodyWithDefaults() *MediaInputBody {
	this := MediaInputBody{}
	return &this
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *MediaInputBody) GetLabels() int64 {
	if o == nil || IsNil(o.Labels) {
		var ret int64
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaInputBody) GetLabelsOk() (*int64, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *MediaInputBody) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given int64 and assigns it to the Labels field.
func (o *MediaInputBody) SetLabels(v int64) {
	o.Labels = &v
}

// GetRibbonMetres returns the RibbonMetres field value if set, zero value otherwise.
func (o *MediaInputBody) GetRibbonMetres() float64 {
	if o == nil || IsNil(o.RibbonMetres) {
		var ret float64
		return ret
	}
	return *o.RibbonMetres
}

// GetRibbonMetresOk returns a tuple with the RibbonMetres field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaInputBody) GetRibbonMetresOk() (*float64, bool) {
	if o == nil || IsNil(o.RibbonMetres) {
		return nil, false
	}
	return o.RibbonMetres, true
}

// HasRibbonMetres returns a boolean if a field has been set.
func (o *MediaInputBody) HasRibbonMetres() bool {
	if o != nil && !IsNil(o.RibbonMetres) {
		return true
	}

	return false
}

// SetRibbonMetres gets a reference to the given float64 and assigns it to the RibbonMetres field.
func (o *MediaInputBody) SetRibbonMetres(v float64) {
	o.RibbonMetres = &v
}

func (o MediaInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MediaInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.RibbonMetres) {
		toSerialize["ribbonMetres"] = o.RibbonMetres
	}
	return toSerialize, nil
}

type NullableMediaInputBody struct {
	value *MediaInputBody
	isSet bool
}

func (v NullableMediaInputBody) Get() *MediaInputBody {
	return v.value
}

func (v *NullableMediaInputBody) Set(val *MediaInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableMediaInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableMediaInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMediaInputBody(val *MediaInputBody) *NullableMediaInputBody {
	return &NullableMediaInputBody{value: val, isSet: true}
}

func (v NullableMediaInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMediaInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


