/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the JobSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobSummary{}

// JobSummary struct for JobSummary
type JobSummary struct {
	Error *string `json:"error,omitempty"`
	Id int64 `json:"id"`
	LabelCount int64 `json:"labelCount"`
	ReceivedAt time.Time `json:"receivedAt"`
	Source string `json:"source"`
	Status string `json:"status"`
	ZplBytes int64 `json:"zplBytes"`
}

type _JobSummary JobSummary

// NewJobSummary instantiates a new JobSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobSummary(id int64, labelCount int64, receivedAt time.Time, source string, status string, zplBytes int64) *JobSummary {
	this := JobSummary{}
	this.Id = id
	this.LabelCount = labelCount
	this.ReceivedAt = receivedAt
	this.Source = source
	this.Status = status
	this.ZplBytes = zplBytes
	return &this
}

// NewJobSummaryWithDefaults instantiates a new JobSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobSummaryWithDefaults() *JobSummary {
	this := JobSummary{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *JobSummary) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JobSummary) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *JobSummary) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *JobSummary) SetError(v string) {
	o.Error = &v
}

// GetId returns the Id field value
func (o *JobSummary) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *JobSummary) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *JobSummary) SetId(v int64) {
	o.Id = v
}

// GetLabelCount returns the LabelCount field value
func (o *JobSummary) GetLabelCount() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LabelCount
}

// GetLabelCountOk returns a tuple with the LabelCount field value
// and a boolean to check if the value has been set.
func (o *JobSummary) GetLabelCountOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LabelCount, true
}

// SetLabelCount sets field value
func (o *JobSummary) SetLabelCount(v int64) {
	o.LabelCount = v
}

// GetReceivedAt returns the ReceivedAt field value
func (o *JobSummary) GetReceivedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ReceivedAt
}

// GetReceivedAtOk returns a tuple with the ReceivedAt field value
// and a boolean to check if the value has been set.
func (o *JobSummary) GetReceivedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceivedAt, true
}

// SetReceivedAt sets field value
func (o *JobSummary) SetReceivedAt(v time.Time) {
	o.ReceivedAt = v
}

// GetSource returns the Source field value
func (o *JobSummary) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *JobSummary) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *JobSummary) SetSource(v string) {
	o.Source = v
}

// GetStatus returns the Status field value
func (o *JobSummary) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *JobSummary) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *JobSummary) SetStatus(v string) {
	o.Status = v
}

// GetZplBytes returns the ZplBytes field value
func (o *JobSummary) GetZplBytes() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ZplBytes
}

// GetZplBytesOk returns a tuple with the ZplBytes field value
// and a boolean to check if the value has been set.
func (o *JobSummary) GetZplBytesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZplBytes, true
}

// SetZplBytes sets field value
func (o *JobSummary) SetZplBytes(v int64) {
	o.ZplBytes = v
}

func (o JobSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	toSerialize["id"] = o.Id
	toSerialize["labelCount"] = o.LabelCount
	toSerialize["receivedAt"] = o.ReceivedAt
	toSerialize["source"] = o.Source
	toSerialize["status"] = o.Status
	toSerialize["zplBytes"] = o.ZplBytes
	return toSerialize, nil
}

func (o *JobSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"labelCount",
		"receivedAt",
		"source",
		"status",
		"zplBytes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobSummary := _JobSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobSummary)

	if err != nil {
		return err
	}

	*o = JobSummary(varJobSummary)

	return err
}

type NullableJobSummary struct {
	value *JobSummary
	isSet bool
}

func (v NullableJobSummary) Get() *JobSummary {
	return v.value
}

func (v *NullableJobSummary) Set(val *JobSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableJobSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableJobSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobSummary(val *JobSummary) *NullableJobSummary {
	return &NullableJobSummary{value: val, isSet: true}
}

func (v NullableJobSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


