/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnicodeOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnicodeOutputBody{}

// UnicodeOutputBody struct for UnicodeOutputBody
type UnicodeOutputBody struct {
	FieldsRasterized int64 `json:"fieldsRasterized"`
	Skipped []string `json:"skipped,omitempty"`
	Zpl string `json:"zpl"`
}

type _UnicodeOutputBody UnicodeOutputBody

// NewUnicodeOutputBody instantiates a new UnicodeOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnicodeOutputBody(fieldsRasterized int64, zpl string) *UnicodeOutputBody {
	this := UnicodeOutputBody{}
	this.FieldsRasterized = fieldsRasterized
	this.Zpl = zpl
	return &this
}

// NewUnicodeOutputBodyWithDefaults instantiates a new UnicodeOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnicodeOutputBodyWithDefaults() *UnicodeOutputBody {
	this := UnicodeOutputBody{}
	return &this
}

// GetFieldsRasterized returns the FieldsRasterized field value
func (o *UnicodeOutputBody) GetFieldsRasterized() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FieldsRasterized
}

// GetFieldsRasterizedOk returns a tuple with the FieldsRasterized field value
// and a boolean to check if the value has been set.
func (o *UnicodeOutputBody) GetFieldsRasterizedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FieldsRasterized, true
}

// SetFieldsRasterized sets field value
func (o *UnicodeOutputBody) SetFieldsRasterized(v int64) {
	o.FieldsRasterized = v
}

// GetSkipped returns the Skipped field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UnicodeOutputBody) GetSkipped() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Skipped
}

// GetSkippedOk returns a tuple with the Skipped field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UnicodeOutputBody) GetSkippedOk() ([]string, bool) {
	if o == nil || IsNil(o.Skipped) {
		return nil, false
	}
	return o.Skipped, true
}

// HasSkipped returns a boolean if a field has been set.
func (o *UnicodeOutputBody) HasSkipped() bool {
	if o != nil && !IsNil(o.Skipped) {
		return true
	}

	return false
}

// SetSkipped gets a reference to the given []string and assigns it to the Skipped field.
func (o *UnicodeOutputBody) SetSkipped(v []string) {
	o.Skipped = v
}

// GetZpl returns the Zpl field value
func (o *UnicodeOutputBody) GetZpl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Zpl
}

// GetZplOk returns a tuple with the Zpl field value
// and a boolean to check if the value has been set.
func (o *UnicodeOutputBody) GetZplOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zpl, true
}

// SetZpl sets field value
func (o *UnicodeOutputBody) SetZpl(v string) {
	o.Zpl = v
}

func (o UnicodeOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnicodeOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fieldsRasterized"] = o.FieldsRasterized
	if o.Skipped != nil {
		toSerialize["skipped"] = o.Skipped
	}
	toSerialize["zpl"] = o.Zpl
	return toSerialize, nil
}

func (o *UnicodeOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fieldsRasterized",
		"zpl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnicodeOutputBody := _UnicodeOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnicodeOutputBody)

	if err != nil {
		return err
	}

	*o = UnicodeOutputBody(varUnicodeOutputBody)

	return err
}

type NullableUnicodeOutputBody struct {
	value *UnicodeOutputBody
	isSet bool
}

func (v NullableUnicodeOutputBody) Get() *UnicodeOutputBody {
	return v.value
}

func (v *NullableUnicodeOutputBody) Set(val *UnicodeOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableUnicodeOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableUnicodeOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnicodeOutputBody(val *UnicodeOutputBody) *NullableUnicodeOutputBody {
	return &NullableUnicodeOutputBody{value: val, isSet: true}
}

func (v NullableUnicodeOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnicodeOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


