/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComposeInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComposeInputBody{}

// ComposeInputBody struct for ComposeInputBody
type ComposeInputBody struct {
	Dpmm *int64 `json:"dpmm,omitempty"`
	Elements []Element `json:"elements"`
	HeightMm *float64 `json:"heightMm,omitempty"`
	// Named label size; alternative to widthMm/heightMm
	Preset *string `json:"preset,omitempty"`
	// Also render the composed label to PNG
	Preview *bool `json:"preview,omitempty"`
	// Values for {{name}} references
	Variables map[string]string `json:"variables,omitempty"`
	WidthMm *float64 `json:"widthMm,omitempty"`
}

type _ComposeInputBody ComposeInputBody

// NewComposeInputBody instantiates a new ComposeInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComposeInputBody(elements []Element) *ComposeInputBody {
	this := ComposeInputBody{}
	this.Elements = elements
	return &this
}

// NewComposeInputBodyWithDefaults instantiates a new ComposeInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComposeInputBodyWithDefaults() *ComposeInputBody {
	this := ComposeInputBody{}
	return &this
}

// GetDpmm returns the Dpmm field value if set, zero value otherwise.
func (o *ComposeInputBody) GetDpmm() int64 {
	if o == nil || IsNil(o.Dpmm) {
		var ret int64
		return ret
	}
	return *o.Dpmm
}

// GetDpmmOk returns a tuple with the Dpmm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComposeInputBody) GetDpmmOk() (*int64, bool) {
	if o == nil || IsNil(o.Dpmm) {
		return nil, false
	}
	return o.Dpmm, true
}

// HasDpmm returns a boolean if a field has been set.
func (o *ComposeInputBody) HasDpmm() bool {
	if o != nil && !IsNil(o.Dpmm) {
		return true
	}

	return false
}

// SetDpmm gets a reference to the given int64 and assigns it to the Dpmm field.
func (o *ComposeInputBody) SetDpmm(v int64) {
	o.Dpmm = &v
}

// GetElements returns the Elements field value
// If the value is explicit nil, the zero value for []Element will be returned
func (o *ComposeInputBody) GetElements() []Element {
	if o == nil {
		var ret []Element
		return ret
	}

	return o.Elements
}

// GetElementsOk returns a tuple with the Elements field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ComposeInputBody) GetElementsOk() ([]Element, bool) {
	if o == nil || IsNil(o.Elements) {
		return nil, false
	}
	return o.Elements, true
}

// SetElements sets field value
func (o *ComposeInputBody) SetElements(v []Element) {
	o.Elements = v
}

// GetHeightMm returns the HeightMm field value if set, zero value otherwise.
func (o *ComposeInputBody) GetHeightMm() float64 {
	if o == nil || IsNil(o.HeightMm) {
		var ret float64
		return ret
	}
	return *o.HeightMm
}

// GetHeightMmOk returns a tuple with the HeightMm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComposeInputBody) GetHeightMmOk() (*float64, bool) {
	if o == nil || IsNil(o.HeightMm) {
		return nil, false
	}
	return o.HeightMm, true
}

// HasHeightMm returns a boolean if a field has been set.
func (o *ComposeInputBody) HasHeightMm() bool {
	if o != nil && !IsNil(o.HeightMm) {
		return true
	}

	return false
}

// SetHeightMm gets a reference to the given float64 and assigns it to the HeightMm field.
func (o *ComposeInputBody) SetHeightMm(v float64) {
	o.HeightMm = &v
}

// GetPreset returns the Preset field value if set, zero value otherwise.
func (o *ComposeInputBody) GetPreset() string {
	if o == nil || IsNil(o.Preset) {
		var ret string
		return ret
	}
	return *o.Preset
}

// GetPresetOk returns a tuple with the Preset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComposeInputBody) GetPresetOk() (*string, bool) {
	if o == nil || IsNil(o.Preset) {
		return nil, false
	}
	return o.Preset, true
}

// HasPreset returns a boolean if a field has been set.
func (o *ComposeInputBody) HasPreset() bool {
	if o != nil && !IsNil(o.Preset) {
		return true
	}

	return false
}

// SetPreset gets a reference to the given string and assigns it to the Preset field.
func (o *ComposeInputBody) SetPreset(v string) {
	o.Preset = &v
}

// GetPreview returns the Preview field value if set, zero value otherwise.
func (o *ComposeInputBody) GetPreview() bool {
	if o == nil || IsNil(o.Preview) {
		var ret bool
		return ret
	}
	return *o.Preview
}

// GetPreviewOk returns a tuple with the Preview field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComposeInputBody) GetPreviewOk() (*bool, bool) {
	if o == nil || IsNil(o.Preview) {
		return nil, false
	}
	return o.Preview, true
}

// HasPreview returns a boolean if a field has been set.
func (o *ComposeInputBody) HasPreview() bool {
	if o != nil && !IsNil(o.Preview) {
		return true
	}

	return false
}

// SetPreview gets a reference to the given bool and assigns it to the Preview field.
func (o *ComposeInputBody) SetPreview(v bool) {
	o.Preview = &v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *ComposeInputBody) GetVariables() map[string]string {
	if o == nil || IsNil(o.Variables) {
		var ret map[string]string
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComposeInputBody) GetVariablesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Variables) {
		return map[string]string{}, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *ComposeInputBody) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given map[string]string and assigns it to the Variables field.
func (o *ComposeInputBody) SetVariables(v map[string]string) {
	o.Variables = v
}

// GetWidthMm returns the WidthMm field value if set, zero value otherwise.
func (o *ComposeInputBody) GetWidthMm() float64 {
	if o == nil || IsNil(o.WidthMm) {
		var ret float64
		return ret
	}
	return *o.WidthMm
}

// GetWidthMmOk returns a tuple with the WidthMm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComposeInputBody) GetWidthMmOk() (*float64, bool) {
	if o == nil || IsNil(o.WidthMm) {
		return nil, false
	}
	return o.WidthMm, true
}

// HasWidthMm returns a boolean if a field has been set.
func (o *ComposeInputBody) HasWidthMm() bool {
	if o != nil && !IsNil(o.WidthMm) {
		return true
	}

	return false
}

// SetWidthMm gets a reference to the given float64 and assigns it to the WidthMm field.
func (o *ComposeInputBody) SetWidthMm(v float64) {
	o.WidthMm = &v
}

func (o ComposeInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComposeInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dpmm) {
		toSerialize["dpmm"] = o.Dpmm
	}
	if o.Elements != nil {
		toSerialize["elements"] = o.Elements
	}
	if !IsNil(o.HeightMm) {
		toSerialize["heightMm"] = o.HeightMm
	}
	if !IsNil(o.Preset) {
		toSerialize["preset"] = o.Preset
	}
	if !IsNil(o.Preview) {
		toSerialize["preview"] = o.Preview
	}
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	if !IsNil(o.WidthMm) {
		toSerialize["widthMm"] = o.WidthMm
	}
	return toSerialize, nil
}

func (o *ComposeInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"elements",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComposeInputBody := _ComposeInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComposeInputBody)

	if err != nil {
		return err
	}

	*o = ComposeInputBody(varComposeInputBody)

	return err
}

type NullableComposeInputBody struct {
	value *ComposeInputBody
	isSet bool
}

func (v NullableComposeInputBody) Get() *ComposeInputBody {
	return v.value
}

func (v *NullableComposeInputBody) Set(val *ComposeInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableComposeInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableComposeInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComposeInputBody(val *ComposeInputBody) *NullableComposeInputBody {
	return &NullableComposeInputBody{value: val, isSet: true}
}

func (v NullableComposeInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComposeInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


