/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
)

// checks if the Supplies type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Supplies{}

// Supplies struct for Supplies
type Supplies struct {
	// Labels left on the roll
	LabelsLeft *int64 `json:"labelsLeft,omitempty"`
	// Labels the roll held when it was fitted; 0 means an endless roll
	LabelsLoaded *int64 `json:"labelsLoaded,omitempty"`
	// Millimetres of ribbon left
	RibbonMmLeft *int64 `json:"ribbonMmLeft,omitempty"`
	// Millimetres of ribbon fitted; 0 means endless, which is also what direct thermal looks like
	RibbonMmLoaded *int64 `json:"ribbonMmLoaded,omitempty"`
}

// NewSupplies instantiates a new Supplies object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSupplies() *Supplies {
	this := Supplies{}
	return &this
}

// NewSuppliesWithDefaults instantiates a new Supplies object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSuppliesWithDefaults() *Supplies {
	this := Supplies{}
	return &this
}

// GetLabelsLeft returns the LabelsLeft field value if set, zero value otherwise.
func (o *Supplies) GetLabelsLeft() int64 {
	if o == nil || IsNil(o.LabelsLeft) {
		var ret int64
		return ret
	}
	return *o.LabelsLeft
}

// GetLabelsLeftOk returns a tuple with the LabelsLeft field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Supplies) GetLabelsLeftOk() (*int64, bool) {
	if o == nil || IsNil(o.LabelsLeft) {
		return nil, false
	}
	return o.LabelsLeft, true
}

// HasLabelsLeft returns a boolean if a field has been set.
func (o *Supplies) HasLabelsLeft() bool {
	if o != nil && !IsNil(o.LabelsLeft) {
		return true
	}

	return false
}

// SetLabelsLeft gets a reference to the given int64 and assigns it to the LabelsLeft field.
func (o *Supplies) SetLabelsLeft(v int64) {
	o.LabelsLeft = &v
}

// GetLabelsLoaded returns the LabelsLoaded field value if set, zero value otherwise.
func (o *Supplies) GetLabelsLoaded() int64 {
	if o == nil || IsNil(o.LabelsLoaded) {
		var ret int64
		return ret
	}
	return *o.LabelsLoaded
}

// GetLabelsLoadedOk returns a tuple with the LabelsLoaded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Supplies) GetLabelsLoadedOk() (*int64, bool) {
	if o == nil || IsNil(o.LabelsLoaded) {
		return nil, false
	}
	return o.LabelsLoaded, true
}

// HasLabelsLoaded returns a boolean if a field has been set.
func (o *Supplies) HasLabelsLoaded() bool {
	if o != nil && !IsNil(o.LabelsLoaded) {
		return true
	}

	return false
}

// SetLabelsLoaded gets a reference to the given int64 and assigns it to the LabelsLoaded field.
func (o *Supplies) SetLabelsLoaded(v int64) {
	o.LabelsLoaded = &v
}

// GetRibbonMmLeft returns the RibbonMmLeft field value if set, zero value otherwise.
func (o *Supplies) GetRibbonMmLeft() int64 {
	if o == nil || IsNil(o.RibbonMmLeft) {
		var ret int64
		return ret
	}
	return *o.RibbonMmLeft
}

// GetRibbonMmLeftOk returns a tuple with the RibbonMmLeft field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Supplies) GetRibbonMmLeftOk() (*int64, bool) {
	if o == nil || IsNil(o.RibbonMmLeft) {
		return nil, false
	}
	return o.RibbonMmLeft, true
}

// HasRibbonMmLeft returns a boolean if a field has been set.
func (o *Supplies) HasRibbonMmLeft() bool {
	if o != nil && !IsNil(o.RibbonMmLeft) {
		return true
	}

	return false
}

// SetRibbonMmLeft gets a reference to the given int64 and assigns it to the RibbonMmLeft field.
func (o *Supplies) SetRibbonMmLeft(v int64) {
	o.RibbonMmLeft = &v
}

// GetRibbonMmLoaded returns the RibbonMmLoaded field value if set, zero value otherwise.
func (o *Supplies) GetRibbonMmLoaded() int64 {
	if o == nil || IsNil(o.RibbonMmLoaded) {
		var ret int64
		return ret
	}
	return *o.RibbonMmLoaded
}

// GetRibbonMmLoadedOk returns a tuple with the RibbonMmLoaded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Supplies) GetRibbonMmLoadedOk() (*int64, bool) {
	if o == nil || IsNil(o.RibbonMmLoaded) {
		return nil, false
	}
	return o.RibbonMmLoaded, true
}

// HasRibbonMmLoaded returns a boolean if a field has been set.
func (o *Supplies) HasRibbonMmLoaded() bool {
	if o != nil && !IsNil(o.RibbonMmLoaded) {
		return true
	}

	return false
}

// SetRibbonMmLoaded gets a reference to the given int64 and assigns it to the RibbonMmLoaded field.
func (o *Supplies) SetRibbonMmLoaded(v int64) {
	o.RibbonMmLoaded = &v
}

func (o Supplies) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Supplies) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LabelsLeft) {
		toSerialize["labelsLeft"] = o.LabelsLeft
	}
	if !IsNil(o.LabelsLoaded) {
		toSerialize["labelsLoaded"] = o.LabelsLoaded
	}
	if !IsNil(o.RibbonMmLeft) {
		toSerialize["ribbonMmLeft"] = o.RibbonMmLeft
	}
	if !IsNil(o.RibbonMmLoaded) {
		toSerialize["ribbonMmLoaded"] = o.RibbonMmLoaded
	}
	return toSerialize, nil
}

type NullableSupplies struct {
	value *Supplies
	isSet bool
}

func (v NullableSupplies) Get() *Supplies {
	return v.value
}

func (v *NullableSupplies) Set(val *Supplies) {
	v.value = val
	v.isSet = true
}

func (v NullableSupplies) IsSet() bool {
	return v.isSet
}

func (v *NullableSupplies) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSupplies(val *Supplies) *NullableSupplies {
	return &NullableSupplies{value: val, isSet: true}
}

func (v NullableSupplies) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSupplies) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


