/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConvertedPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConvertedPage{}

// ConvertedPage struct for ConvertedPage
type ConvertedPage struct {
	// 1-based page number
	Page int64 `json:"page"`
	Zpl string `json:"zpl"`
}

type _ConvertedPage ConvertedPage

// NewConvertedPage instantiates a new ConvertedPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConvertedPage(page int64, zpl string) *ConvertedPage {
	this := ConvertedPage{}
	this.Page = page
	this.Zpl = zpl
	return &this
}

// NewConvertedPageWithDefaults instantiates a new ConvertedPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConvertedPageWithDefaults() *ConvertedPage {
	this := ConvertedPage{}
	return &this
}

// GetPage returns the Page field value
func (o *ConvertedPage) GetPage() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *ConvertedPage) GetPageOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *ConvertedPage) SetPage(v int64) {
	o.Page = v
}

// GetZpl returns the Zpl field value
func (o *ConvertedPage) GetZpl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Zpl
}

// GetZplOk returns a tuple with the Zpl field value
// and a boolean to check if the value has been set.
func (o *ConvertedPage) GetZplOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zpl, true
}

// SetZpl sets field value
func (o *ConvertedPage) SetZpl(v string) {
	o.Zpl = v
}

func (o ConvertedPage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConvertedPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["page"] = o.Page
	toSerialize["zpl"] = o.Zpl
	return toSerialize, nil
}

func (o *ConvertedPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"page",
		"zpl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConvertedPage := _ConvertedPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConvertedPage)

	if err != nil {
		return err
	}

	*o = ConvertedPage(varConvertedPage)

	return err
}

type NullableConvertedPage struct {
	value *ConvertedPage
	isSet bool
}

func (v NullableConvertedPage) Get() *ConvertedPage {
	return v.value
}

func (v *NullableConvertedPage) Set(val *ConvertedPage) {
	v.value = val
	v.isSet = true
}

func (v NullableConvertedPage) IsSet() bool {
	return v.isSet
}

func (v *NullableConvertedPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConvertedPage(val *ConvertedPage) *NullableConvertedPage {
	return &NullableConvertedPage{value: val, isSet: true}
}

func (v NullableConvertedPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConvertedPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


