/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RenderedLabel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RenderedLabel{}

// RenderedLabel struct for RenderedLabel
type RenderedLabel struct {
	HeightPx int64 `json:"heightPx"`
	Index int64 `json:"index"`
	// Base64-encoded PNG
	Png string `json:"png"`
	WidthPx int64 `json:"widthPx"`
}

type _RenderedLabel RenderedLabel

// NewRenderedLabel instantiates a new RenderedLabel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRenderedLabel(heightPx int64, index int64, png string, widthPx int64) *RenderedLabel {
	this := RenderedLabel{}
	this.HeightPx = heightPx
	this.Index = index
	this.Png = png
	this.WidthPx = widthPx
	return &this
}

// NewRenderedLabelWithDefaults instantiates a new RenderedLabel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRenderedLabelWithDefaults() *RenderedLabel {
	this := RenderedLabel{}
	return &this
}

// GetHeightPx returns the HeightPx field value
func (o *RenderedLabel) GetHeightPx() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.HeightPx
}

// GetHeightPxOk returns a tuple with the HeightPx field value
// and a boolean to check if the value has been set.
func (o *RenderedLabel) GetHeightPxOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HeightPx, true
}

// SetHeightPx sets field value
func (o *RenderedLabel) SetHeightPx(v int64) {
	o.HeightPx = v
}

// GetIndex returns the Index field value
func (o *RenderedLabel) GetIndex() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *RenderedLabel) GetIndexOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *RenderedLabel) SetIndex(v int64) {
	o.Index = v
}

// GetPng returns the Png field value
func (o *RenderedLabel) GetPng() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Png
}

// GetPngOk returns a tuple with the Png field value
// and a boolean to check if the value has been set.
func (o *RenderedLabel) GetPngOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Png, true
}

// SetPng sets field value
func (o *RenderedLabel) SetPng(v string) {
	o.Png = v
}

// GetWidthPx returns the WidthPx field value
func (o *RenderedLabel) GetWidthPx() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.WidthPx
}

// GetWidthPxOk returns a tuple with the WidthPx field value
// and a boolean to check if the value has been set.
func (o *RenderedLabel) GetWidthPxOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WidthPx, true
}

// SetWidthPx sets field value
func (o *RenderedLabel) SetWidthPx(v int64) {
	o.WidthPx = v
}

func (o RenderedLabel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RenderedLabel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["heightPx"] = o.HeightPx
	toSerialize["index"] = o.Index
	toSerialize["png"] = o.Png
	toSerialize["widthPx"] = o.WidthPx
	return toSerialize, nil
}

func (o *RenderedLabel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"heightPx",
		"index",
		"png",
		"widthPx",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRenderedLabel := _RenderedLabel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRenderedLabel)

	if err != nil {
		return err
	}

	*o = RenderedLabel(varRenderedLabel)

	return err
}

type NullableRenderedLabel struct {
	value *RenderedLabel
	isSet bool
}

func (v NullableRenderedLabel) Get() *RenderedLabel {
	return v.value
}

func (v *NullableRenderedLabel) Set(val *RenderedLabel) {
	v.value = val
	v.isSet = true
}

func (v NullableRenderedLabel) IsSet() bool {
	return v.isSet
}

func (v *NullableRenderedLabel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRenderedLabel(val *RenderedLabel) *NullableRenderedLabel {
	return &NullableRenderedLabel{value: val, isSet: true}
}

func (v NullableRenderedLabel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRenderedLabel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


