/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VoidInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoidInputBody{}

// VoidInputBody struct for VoidInputBody
type VoidInputBody struct {
	Dpmm *int64 `json:"dpmm,omitempty"`
	HeightMm *float64 `json:"heightMm,omitempty"`
	// Named label size in inches; alternative to widthMm/heightMm
	Preset *string `json:"preset,omitempty"`
	// Attribution stamp, e.g. VOID: bfaerber
	Stamp *string `json:"stamp,omitempty"`
	// Warning text; default VOID - DO NOT MAIL
	Text *string `json:"text,omitempty"`
	WidthMm *float64 `json:"widthMm,omitempty"`
	Zpl string `json:"zpl"`
}

type _VoidInputBody VoidInputBody

// NewVoidInputBody instantiates a new VoidInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoidInputBody(zpl string) *VoidInputBody {
	this := VoidInputBody{}
	this.Zpl = zpl
	return &this
}

// NewVoidInputBodyWithDefaults instantiates a new VoidInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoidInputBodyWithDefaults() *VoidInputBody {
	this := VoidInputBody{}
	return &this
}

// GetDpmm returns the Dpmm field value if set, zero value otherwise.
func (o *VoidInputBody) GetDpmm() int64 {
	if o == nil || IsNil(o.Dpmm) {
		var ret int64
		return ret
	}
	return *o.Dpmm
}

// GetDpmmOk returns a tuple with the Dpmm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoidInputBody) GetDpmmOk() (*int64, bool) {
	if o == nil || IsNil(o.Dpmm) {
		return nil, false
	}
	return o.Dpmm, true
}

// HasDpmm returns a boolean if a field has been set.
func (o *VoidInputBody) HasDpmm() bool {
	if o != nil && !IsNil(o.Dpmm) {
		return true
	}

	return false
}

// SetDpmm gets a reference to the given int64 and assigns it to the Dpmm field.
func (o *VoidInputBody) SetDpmm(v int64) {
	o.Dpmm = &v
}

// GetHeightMm returns the HeightMm field value if set, zero value otherwise.
func (o *VoidInputBody) GetHeightMm() float64 {
	if o == nil || IsNil(o.HeightMm) {
		var ret float64
		return ret
	}
	return *o.HeightMm
}

// GetHeightMmOk returns a tuple with the HeightMm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoidInputBody) GetHeightMmOk() (*float64, bool) {
	if o == nil || IsNil(o.HeightMm) {
		return nil, false
	}
	return o.HeightMm, true
}

// HasHeightMm returns a boolean if a field has been set.
func (o *VoidInputBody) HasHeightMm() bool {
	if o != nil && !IsNil(o.HeightMm) {
		return true
	}

	return false
}

// SetHeightMm gets a reference to the given float64 and assigns it to the HeightMm field.
func (o *VoidInputBody) SetHeightMm(v float64) {
	o.HeightMm = &v
}

// GetPreset returns the Preset field value if set, zero value otherwise.
func (o *VoidInputBody) GetPreset() string {
	if o == nil || IsNil(o.Preset) {
		var ret string
		return ret
	}
	return *o.Preset
}

// GetPresetOk returns a tuple with the Preset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoidInputBody) GetPresetOk() (*string, bool) {
	if o == nil || IsNil(o.Preset) {
		return nil, false
	}
	return o.Preset, true
}

// HasPreset returns a boolean if a field has been set.
func (o *VoidInputBody) HasPreset() bool {
	if o != nil && !IsNil(o.Preset) {
		return true
	}

	return false
}

// SetPreset gets a reference to the given string and assigns it to the Preset field.
func (o *VoidInputBody) SetPreset(v string) {
	o.Preset = &v
}

// GetStamp returns the Stamp field value if set, zero value otherwise.
func (o *VoidInputBody) GetStamp() string {
	if o == nil || IsNil(o.Stamp) {
		var ret string
		return ret
	}
	return *o.Stamp
}

// GetStampOk returns a tuple with the Stamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoidInputBody) GetStampOk() (*string, bool) {
	if o == nil || IsNil(o.Stamp) {
		return nil, false
	}
	return o.Stamp, true
}

// HasStamp returns a boolean if a field has been set.
func (o *VoidInputBody) HasStamp() bool {
	if o != nil && !IsNil(o.Stamp) {
		return true
	}

	return false
}

// SetStamp gets a reference to the given string and assigns it to the Stamp field.
func (o *VoidInputBody) SetStamp(v string) {
	o.Stamp = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *VoidInputBody) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoidInputBody) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *VoidInputBody) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *VoidInputBody) SetText(v string) {
	o.Text = &v
}

// GetWidthMm returns the WidthMm field value if set, zero value otherwise.
func (o *VoidInputBody) GetWidthMm() float64 {
	if o == nil || IsNil(o.WidthMm) {
		var ret float64
		return ret
	}
	return *o.WidthMm
}

// GetWidthMmOk returns a tuple with the WidthMm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VoidInputBody) GetWidthMmOk() (*float64, bool) {
	if o == nil || IsNil(o.WidthMm) {
		return nil, false
	}
	return o.WidthMm, true
}

// HasWidthMm returns a boolean if a field has been set.
func (o *VoidInputBody) HasWidthMm() bool {
	if o != nil && !IsNil(o.WidthMm) {
		return true
	}

	return false
}

// SetWidthMm gets a reference to the given float64 and assigns it to the WidthMm field.
func (o *VoidInputBody) SetWidthMm(v float64) {
	o.WidthMm = &v
}

// GetZpl returns the Zpl field value
func (o *VoidInputBody) GetZpl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Zpl
}

// GetZplOk returns a tuple with the Zpl field value
// and a boolean to check if the value has been set.
func (o *VoidInputBody) GetZplOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zpl, true
}

// SetZpl sets field value
func (o *VoidInputBody) SetZpl(v string) {
	o.Zpl = v
}

func (o VoidInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoidInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dpmm) {
		toSerialize["dpmm"] = o.Dpmm
	}
	if !IsNil(o.HeightMm) {
		toSerialize["heightMm"] = o.HeightMm
	}
	if !IsNil(o.Preset) {
		toSerialize["preset"] = o.Preset
	}
	if !IsNil(o.Stamp) {
		toSerialize["stamp"] = o.Stamp
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.WidthMm) {
		toSerialize["widthMm"] = o.WidthMm
	}
	toSerialize["zpl"] = o.Zpl
	return toSerialize, nil
}

func (o *VoidInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"zpl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVoidInputBody := _VoidInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVoidInputBody)

	if err != nil {
		return err
	}

	*o = VoidInputBody(varVoidInputBody)

	return err
}

type NullableVoidInputBody struct {
	value *VoidInputBody
	isSet bool
}

func (v NullableVoidInputBody) Get() *VoidInputBody {
	return v.value
}

func (v *NullableVoidInputBody) Set(val *VoidInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableVoidInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableVoidInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoidInputBody(val *VoidInputBody) *NullableVoidInputBody {
	return &NullableVoidInputBody{value: val, isSet: true}
}

func (v NullableVoidInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoidInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


