/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StateOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StateOutputBody{}

// StateOutputBody struct for StateOutputBody
type StateOutputBody struct {
	State StatusSnapshot `json:"state"`
}

type _StateOutputBody StateOutputBody

// NewStateOutputBody instantiates a new StateOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStateOutputBody(state StatusSnapshot) *StateOutputBody {
	this := StateOutputBody{}
	this.State = state
	return &this
}

// NewStateOutputBodyWithDefaults instantiates a new StateOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStateOutputBodyWithDefaults() *StateOutputBody {
	this := StateOutputBody{}
	return &this
}

// GetState returns the State field value
func (o *StateOutputBody) GetState() StatusSnapshot {
	if o == nil {
		var ret StatusSnapshot
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *StateOutputBody) GetStateOk() (*StatusSnapshot, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *StateOutputBody) SetState(v StatusSnapshot) {
	o.State = v
}

func (o StateOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StateOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *StateOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStateOutputBody := _StateOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStateOutputBody)

	if err != nil {
		return err
	}

	*o = StateOutputBody(varStateOutputBody)

	return err
}

type NullableStateOutputBody struct {
	value *StateOutputBody
	isSet bool
}

func (v NullableStateOutputBody) Get() *StateOutputBody {
	return v.value
}

func (v *NullableStateOutputBody) Set(val *StateOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableStateOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableStateOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStateOutputBody(val *StateOutputBody) *NullableStateOutputBody {
	return &NullableStateOutputBody{value: val, isSet: true}
}

func (v NullableStateOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStateOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


