/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StampInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StampInputBody{}

// StampInputBody struct for StampInputBody
type StampInputBody struct {
	// PNG/GIF/JPEG, base64-encoded
	Image string `json:"image"`
	// Stamp width in dots; 0 keeps the image's natural size
	WidthDots *int64 `json:"widthDots,omitempty"`
	// Left edge in dots
	X *int64 `json:"x,omitempty"`
	// Top edge in dots
	Y *int64 `json:"y,omitempty"`
	Zpl string `json:"zpl"`
}

type _StampInputBody StampInputBody

// NewStampInputBody instantiates a new StampInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStampInputBody(image string, zpl string) *StampInputBody {
	this := StampInputBody{}
	this.Image = image
	this.Zpl = zpl
	return &this
}

// NewStampInputBodyWithDefaults instantiates a new StampInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStampInputBodyWithDefaults() *StampInputBody {
	this := StampInputBody{}
	return &this
}

// GetImage returns the Image field value
func (o *StampInputBody) GetImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *StampInputBody) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *StampInputBody) SetImage(v string) {
	o.Image = v
}

// GetWidthDots returns the WidthDots field value if set, zero value otherwise.
func (o *StampInputBody) GetWidthDots() int64 {
	if o == nil || IsNil(o.WidthDots) {
		var ret int64
		return ret
	}
	return *o.WidthDots
}

// GetWidthDotsOk returns a tuple with the WidthDots field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StampInputBody) GetWidthDotsOk() (*int64, bool) {
	if o == nil || IsNil(o.WidthDots) {
		return nil, false
	}
	return o.WidthDots, true
}

// HasWidthDots returns a boolean if a field has been set.
func (o *StampInputBody) HasWidthDots() bool {
	if o != nil && !IsNil(o.WidthDots) {
		return true
	}

	return false
}

// SetWidthDots gets a reference to the given int64 and assigns it to the WidthDots field.
func (o *StampInputBody) SetWidthDots(v int64) {
	o.WidthDots = &v
}

// GetX returns the X field value if set, zero value otherwise.
func (o *StampInputBody) GetX() int64 {
	if o == nil || IsNil(o.X) {
		var ret int64
		return ret
	}
	return *o.X
}

// GetXOk returns a tuple with the X field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StampInputBody) GetXOk() (*int64, bool) {
	if o == nil || IsNil(o.X) {
		return nil, false
	}
	return o.X, true
}

// HasX returns a boolean if a field has been set.
func (o *StampInputBody) HasX() bool {
	if o != nil && !IsNil(o.X) {
		return true
	}

	return false
}

// SetX gets a reference to the given int64 and assigns it to the X field.
func (o *StampInputBody) SetX(v int64) {
	o.X = &v
}

// GetY returns the Y field value if set, zero value otherwise.
func (o *StampInputBody) GetY() int64 {
	if o == nil || IsNil(o.Y) {
		var ret int64
		return ret
	}
	return *o.Y
}

// GetYOk returns a tuple with the Y field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StampInputBody) GetYOk() (*int64, bool) {
	if o == nil || IsNil(o.Y) {
		return nil, false
	}
	return o.Y, true
}

// HasY returns a boolean if a field has been set.
func (o *StampInputBody) HasY() bool {
	if o != nil && !IsNil(o.Y) {
		return true
	}

	return false
}

// SetY gets a reference to the given int64 and assigns it to the Y field.
func (o *StampInputBody) SetY(v int64) {
	o.Y = &v
}

// GetZpl returns the Zpl field value
func (o *StampInputBody) GetZpl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Zpl
}

// GetZplOk returns a tuple with the Zpl field value
// and a boolean to check if the value has been set.
func (o *StampInputBody) GetZplOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zpl, true
}

// SetZpl sets field value
func (o *StampInputBody) SetZpl(v string) {
	o.Zpl = v
}

func (o StampInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StampInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["image"] = o.Image
	if !IsNil(o.WidthDots) {
		toSerialize["widthDots"] = o.WidthDots
	}
	if !IsNil(o.X) {
		toSerialize["x"] = o.X
	}
	if !IsNil(o.Y) {
		toSerialize["y"] = o.Y
	}
	toSerialize["zpl"] = o.Zpl
	return toSerialize, nil
}

func (o *StampInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"image",
		"zpl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStampInputBody := _StampInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStampInputBody)

	if err != nil {
		return err
	}

	*o = StampInputBody(varStampInputBody)

	return err
}

type NullableStampInputBody struct {
	value *StampInputBody
	isSet bool
}

func (v NullableStampInputBody) Get() *StampInputBody {
	return v.value
}

func (v *NullableStampInputBody) Set(val *StampInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableStampInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableStampInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStampInputBody(val *StampInputBody) *NullableStampInputBody {
	return &NullableStampInputBody{value: val, isSet: true}
}

func (v NullableStampInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStampInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


