/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HostStatusInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostStatusInputBody{}

// HostStatusInputBody struct for HostStatusInputBody
type HostStatusInputBody struct {
	// The three ~HS status lines, as received
	Response string `json:"response"`
}

type _HostStatusInputBody HostStatusInputBody

// NewHostStatusInputBody instantiates a new HostStatusInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostStatusInputBody(response string) *HostStatusInputBody {
	this := HostStatusInputBody{}
	this.Response = response
	return &this
}

// NewHostStatusInputBodyWithDefaults instantiates a new HostStatusInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostStatusInputBodyWithDefaults() *HostStatusInputBody {
	this := HostStatusInputBody{}
	return &this
}

// GetResponse returns the Response field value
func (o *HostStatusInputBody) GetResponse() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Response
}

// GetResponseOk returns a tuple with the Response field value
// and a boolean to check if the value has been set.
func (o *HostStatusInputBody) GetResponseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Response, true
}

// SetResponse sets field value
func (o *HostStatusInputBody) SetResponse(v string) {
	o.Response = v
}

func (o HostStatusInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostStatusInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["response"] = o.Response
	return toSerialize, nil
}

func (o *HostStatusInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"response",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostStatusInputBody := _HostStatusInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostStatusInputBody)

	if err != nil {
		return err
	}

	*o = HostStatusInputBody(varHostStatusInputBody)

	return err
}

type NullableHostStatusInputBody struct {
	value *HostStatusInputBody
	isSet bool
}

func (v NullableHostStatusInputBody) Get() *HostStatusInputBody {
	return v.value
}

func (v *NullableHostStatusInputBody) Set(val *HostStatusInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableHostStatusInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableHostStatusInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostStatusInputBody(val *HostStatusInputBody) *NullableHostStatusInputBody {
	return &NullableHostStatusInputBody{value: val, isSet: true}
}

func (v NullableHostStatusInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostStatusInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


