/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StatusField type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatusField{}

// StatusField struct for StatusField
type StatusField struct {
	Field string `json:"field"`
	Raw string `json:"raw"`
	Value string `json:"value"`
}

type _StatusField StatusField

// NewStatusField instantiates a new StatusField object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatusField(field string, raw string, value string) *StatusField {
	this := StatusField{}
	this.Field = field
	this.Raw = raw
	this.Value = value
	return &this
}

// NewStatusFieldWithDefaults instantiates a new StatusField object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatusFieldWithDefaults() *StatusField {
	this := StatusField{}
	return &this
}

// GetField returns the Field field value
func (o *StatusField) GetField() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Field
}

// GetFieldOk returns a tuple with the Field field value
// and a boolean to check if the value has been set.
func (o *StatusField) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Field, true
}

// SetField sets field value
func (o *StatusField) SetField(v string) {
	o.Field = v
}

// GetRaw returns the Raw field value
func (o *StatusField) GetRaw() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Raw
}

// GetRawOk returns a tuple with the Raw field value
// and a boolean to check if the value has been set.
func (o *StatusField) GetRawOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Raw, true
}

// SetRaw sets field value
func (o *StatusField) SetRaw(v string) {
	o.Raw = v
}

// GetValue returns the Value field value
func (o *StatusField) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *StatusField) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *StatusField) SetValue(v string) {
	o.Value = v
}

func (o StatusField) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatusField) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["field"] = o.Field
	toSerialize["raw"] = o.Raw
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *StatusField) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"field",
		"raw",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatusField := _StatusField{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStatusField)

	if err != nil {
		return err
	}

	*o = StatusField(varStatusField)

	return err
}

type NullableStatusField struct {
	value *StatusField
	isSet bool
}

func (v NullableStatusField) Get() *StatusField {
	return v.value
}

func (v *NullableStatusField) Set(val *StatusField) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusField) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusField) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusField(val *StatusField) *NullableStatusField {
	return &NullableStatusField{value: val, isSet: true}
}

func (v NullableStatusField) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusField) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


