/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HtmlInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HtmlInputBody{}

// HtmlInputBody struct for HtmlInputBody
type HtmlInputBody struct {
	Compression *string `json:"compression,omitempty"`
	Dpmm *int64 `json:"dpmm,omitempty"`
	HeightMm *float64 `json:"heightMm,omitempty"`
	// Label markup: HTML/CSS plus <zpl-barcode> elements
	Html string `json:"html"`
	Preset *string `json:"preset,omitempty"`
	Threshold *int64 `json:"threshold,omitempty"`
	WidthMm *float64 `json:"widthMm,omitempty"`
}

type _HtmlInputBody HtmlInputBody

// NewHtmlInputBody instantiates a new HtmlInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHtmlInputBody(html string) *HtmlInputBody {
	this := HtmlInputBody{}
	this.Html = html
	return &this
}

// NewHtmlInputBodyWithDefaults instantiates a new HtmlInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHtmlInputBodyWithDefaults() *HtmlInputBody {
	this := HtmlInputBody{}
	return &this
}

// GetCompression returns the Compression field value if set, zero value otherwise.
func (o *HtmlInputBody) GetCompression() string {
	if o == nil || IsNil(o.Compression) {
		var ret string
		return ret
	}
	return *o.Compression
}

// GetCompressionOk returns a tuple with the Compression field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HtmlInputBody) GetCompressionOk() (*string, bool) {
	if o == nil || IsNil(o.Compression) {
		return nil, false
	}
	return o.Compression, true
}

// HasCompression returns a boolean if a field has been set.
func (o *HtmlInputBody) HasCompression() bool {
	if o != nil && !IsNil(o.Compression) {
		return true
	}

	return false
}

// SetCompression gets a reference to the given string and assigns it to the Compression field.
func (o *HtmlInputBody) SetCompression(v string) {
	o.Compression = &v
}

// GetDpmm returns the Dpmm field value if set, zero value otherwise.
func (o *HtmlInputBody) GetDpmm() int64 {
	if o == nil || IsNil(o.Dpmm) {
		var ret int64
		return ret
	}
	return *o.Dpmm
}

// GetDpmmOk returns a tuple with the Dpmm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HtmlInputBody) GetDpmmOk() (*int64, bool) {
	if o == nil || IsNil(o.Dpmm) {
		return nil, false
	}
	return o.Dpmm, true
}

// HasDpmm returns a boolean if a field has been set.
func (o *HtmlInputBody) HasDpmm() bool {
	if o != nil && !IsNil(o.Dpmm) {
		return true
	}

	return false
}

// SetDpmm gets a reference to the given int64 and assigns it to the Dpmm field.
func (o *HtmlInputBody) SetDpmm(v int64) {
	o.Dpmm = &v
}

// GetHeightMm returns the HeightMm field value if set, zero value otherwise.
func (o *HtmlInputBody) GetHeightMm() float64 {
	if o == nil || IsNil(o.HeightMm) {
		var ret float64
		return ret
	}
	return *o.HeightMm
}

// GetHeightMmOk returns a tuple with the HeightMm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HtmlInputBody) GetHeightMmOk() (*float64, bool) {
	if o == nil || IsNil(o.HeightMm) {
		return nil, false
	}
	return o.HeightMm, true
}

// HasHeightMm returns a boolean if a field has been set.
func (o *HtmlInputBody) HasHeightMm() bool {
	if o != nil && !IsNil(o.HeightMm) {
		return true
	}

	return false
}

// SetHeightMm gets a reference to the given float64 and assigns it to the HeightMm field.
func (o *HtmlInputBody) SetHeightMm(v float64) {
	o.HeightMm = &v
}

// GetHtml returns the Html field value
func (o *HtmlInputBody) GetHtml() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Html
}

// GetHtmlOk returns a tuple with the Html field value
// and a boolean to check if the value has been set.
func (o *HtmlInputBody) GetHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Html, true
}

// SetHtml sets field value
func (o *HtmlInputBody) SetHtml(v string) {
	o.Html = v
}

// GetPreset returns the Preset field value if set, zero value otherwise.
func (o *HtmlInputBody) GetPreset() string {
	if o == nil || IsNil(o.Preset) {
		var ret string
		return ret
	}
	return *o.Preset
}

// GetPresetOk returns a tuple with the Preset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HtmlInputBody) GetPresetOk() (*string, bool) {
	if o == nil || IsNil(o.Preset) {
		return nil, false
	}
	return o.Preset, true
}

// HasPreset returns a boolean if a field has been set.
func (o *HtmlInputBody) HasPreset() bool {
	if o != nil && !IsNil(o.Preset) {
		return true
	}

	return false
}

// SetPreset gets a reference to the given string and assigns it to the Preset field.
func (o *HtmlInputBody) SetPreset(v string) {
	o.Preset = &v
}

// GetThreshold returns the Threshold field value if set, zero value otherwise.
func (o *HtmlInputBody) GetThreshold() int64 {
	if o == nil || IsNil(o.Threshold) {
		var ret int64
		return ret
	}
	return *o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HtmlInputBody) GetThresholdOk() (*int64, bool) {
	if o == nil || IsNil(o.Threshold) {
		return nil, false
	}
	return o.Threshold, true
}

// HasThreshold returns a boolean if a field has been set.
func (o *HtmlInputBody) HasThreshold() bool {
	if o != nil && !IsNil(o.Threshold) {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given int64 and assigns it to the Threshold field.
func (o *HtmlInputBody) SetThreshold(v int64) {
	o.Threshold = &v
}

// GetWidthMm returns the WidthMm field value if set, zero value otherwise.
func (o *HtmlInputBody) GetWidthMm() float64 {
	if o == nil || IsNil(o.WidthMm) {
		var ret float64
		return ret
	}
	return *o.WidthMm
}

// GetWidthMmOk returns a tuple with the WidthMm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HtmlInputBody) GetWidthMmOk() (*float64, bool) {
	if o == nil || IsNil(o.WidthMm) {
		return nil, false
	}
	return o.WidthMm, true
}

// HasWidthMm returns a boolean if a field has been set.
func (o *HtmlInputBody) HasWidthMm() bool {
	if o != nil && !IsNil(o.WidthMm) {
		return true
	}

	return false
}

// SetWidthMm gets a reference to the given float64 and assigns it to the WidthMm field.
func (o *HtmlInputBody) SetWidthMm(v float64) {
	o.WidthMm = &v
}

func (o HtmlInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HtmlInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Compression) {
		toSerialize["compression"] = o.Compression
	}
	if !IsNil(o.Dpmm) {
		toSerialize["dpmm"] = o.Dpmm
	}
	if !IsNil(o.HeightMm) {
		toSerialize["heightMm"] = o.HeightMm
	}
	toSerialize["html"] = o.Html
	if !IsNil(o.Preset) {
		toSerialize["preset"] = o.Preset
	}
	if !IsNil(o.Threshold) {
		toSerialize["threshold"] = o.Threshold
	}
	if !IsNil(o.WidthMm) {
		toSerialize["widthMm"] = o.WidthMm
	}
	return toSerialize, nil
}

func (o *HtmlInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"html",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHtmlInputBody := _HtmlInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHtmlInputBody)

	if err != nil {
		return err
	}

	*o = HtmlInputBody(varHtmlInputBody)

	return err
}

type NullableHtmlInputBody struct {
	value *HtmlInputBody
	isSet bool
}

func (v NullableHtmlInputBody) Get() *HtmlInputBody {
	return v.value
}

func (v *NullableHtmlInputBody) Set(val *HtmlInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableHtmlInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableHtmlInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHtmlInputBody(val *HtmlInputBody) *NullableHtmlInputBody {
	return &NullableHtmlInputBody{value: val, isSet: true}
}

func (v NullableHtmlInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHtmlInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


