/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConvertOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConvertOutputBody{}

// ConvertOutputBody struct for ConvertOutputBody
type ConvertOutputBody struct {
	Pages []ConvertedPage `json:"pages"`
}

type _ConvertOutputBody ConvertOutputBody

// NewConvertOutputBody instantiates a new ConvertOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConvertOutputBody(pages []ConvertedPage) *ConvertOutputBody {
	this := ConvertOutputBody{}
	this.Pages = pages
	return &this
}

// NewConvertOutputBodyWithDefaults instantiates a new ConvertOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConvertOutputBodyWithDefaults() *ConvertOutputBody {
	this := ConvertOutputBody{}
	return &this
}

// GetPages returns the Pages field value
// If the value is explicit nil, the zero value for []ConvertedPage will be returned
func (o *ConvertOutputBody) GetPages() []ConvertedPage {
	if o == nil {
		var ret []ConvertedPage
		return ret
	}

	return o.Pages
}

// GetPagesOk returns a tuple with the Pages field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConvertOutputBody) GetPagesOk() ([]ConvertedPage, bool) {
	if o == nil || IsNil(o.Pages) {
		return nil, false
	}
	return o.Pages, true
}

// SetPages sets field value
func (o *ConvertOutputBody) SetPages(v []ConvertedPage) {
	o.Pages = v
}

func (o ConvertOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConvertOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Pages != nil {
		toSerialize["pages"] = o.Pages
	}
	return toSerialize, nil
}

func (o *ConvertOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConvertOutputBody := _ConvertOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConvertOutputBody)

	if err != nil {
		return err
	}

	*o = ConvertOutputBody(varConvertOutputBody)

	return err
}

type NullableConvertOutputBody struct {
	value *ConvertOutputBody
	isSet bool
}

func (v NullableConvertOutputBody) Get() *ConvertOutputBody {
	return v.value
}

func (v *NullableConvertOutputBody) Set(val *ConvertOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableConvertOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableConvertOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConvertOutputBody(val *ConvertOutputBody) *NullableConvertOutputBody {
	return &NullableConvertOutputBody{value: val, isSet: true}
}

func (v NullableConvertOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConvertOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


