/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the JobOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JobOutputBody{}

// JobOutputBody struct for JobOutputBody
type JobOutputBody struct {
	// URLs of the rendered label PNGs
	Labels []string `json:"labels"`
	// The raw ZPL as received
	Zpl string `json:"zpl"`
}

type _JobOutputBody JobOutputBody

// NewJobOutputBody instantiates a new JobOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJobOutputBody(labels []string, zpl string) *JobOutputBody {
	this := JobOutputBody{}
	this.Labels = labels
	this.Zpl = zpl
	return &this
}

// NewJobOutputBodyWithDefaults instantiates a new JobOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJobOutputBodyWithDefaults() *JobOutputBody {
	this := JobOutputBody{}
	return &this
}

// GetLabels returns the Labels field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *JobOutputBody) GetLabels() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JobOutputBody) GetLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// SetLabels sets field value
func (o *JobOutputBody) SetLabels(v []string) {
	o.Labels = v
}

// GetZpl returns the Zpl field value
func (o *JobOutputBody) GetZpl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Zpl
}

// GetZplOk returns a tuple with the Zpl field value
// and a boolean to check if the value has been set.
func (o *JobOutputBody) GetZplOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zpl, true
}

// SetZpl sets field value
func (o *JobOutputBody) SetZpl(v string) {
	o.Zpl = v
}

func (o JobOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JobOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	toSerialize["zpl"] = o.Zpl
	return toSerialize, nil
}

func (o *JobOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"labels",
		"zpl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varJobOutputBody := _JobOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varJobOutputBody)

	if err != nil {
		return err
	}

	*o = JobOutputBody(varJobOutputBody)

	return err
}

type NullableJobOutputBody struct {
	value *JobOutputBody
	isSet bool
}

func (v NullableJobOutputBody) Get() *JobOutputBody {
	return v.value
}

func (v *NullableJobOutputBody) Set(val *JobOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableJobOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableJobOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJobOutputBody(val *JobOutputBody) *NullableJobOutputBody {
	return &NullableJobOutputBody{value: val, isSet: true}
}

func (v NullableJobOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJobOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


