/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListPrintersOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPrintersOutputBody{}

// ListPrintersOutputBody struct for ListPrintersOutputBody
type ListPrintersOutputBody struct {
	Printers []PrinterBody `json:"printers"`
}

type _ListPrintersOutputBody ListPrintersOutputBody

// NewListPrintersOutputBody instantiates a new ListPrintersOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPrintersOutputBody(printers []PrinterBody) *ListPrintersOutputBody {
	this := ListPrintersOutputBody{}
	this.Printers = printers
	return &this
}

// NewListPrintersOutputBodyWithDefaults instantiates a new ListPrintersOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPrintersOutputBodyWithDefaults() *ListPrintersOutputBody {
	this := ListPrintersOutputBody{}
	return &this
}

// GetPrinters returns the Printers field value
// If the value is explicit nil, the zero value for []PrinterBody will be returned
func (o *ListPrintersOutputBody) GetPrinters() []PrinterBody {
	if o == nil {
		var ret []PrinterBody
		return ret
	}

	return o.Printers
}

// GetPrintersOk returns a tuple with the Printers field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListPrintersOutputBody) GetPrintersOk() ([]PrinterBody, bool) {
	if o == nil || IsNil(o.Printers) {
		return nil, false
	}
	return o.Printers, true
}

// SetPrinters sets field value
func (o *ListPrintersOutputBody) SetPrinters(v []PrinterBody) {
	o.Printers = v
}

func (o ListPrintersOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPrintersOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Printers != nil {
		toSerialize["printers"] = o.Printers
	}
	return toSerialize, nil
}

func (o *ListPrintersOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"printers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListPrintersOutputBody := _ListPrintersOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListPrintersOutputBody)

	if err != nil {
		return err
	}

	*o = ListPrintersOutputBody(varListPrintersOutputBody)

	return err
}

type NullableListPrintersOutputBody struct {
	value *ListPrintersOutputBody
	isSet bool
}

func (v NullableListPrintersOutputBody) Get() *ListPrintersOutputBody {
	return v.value
}

func (v *NullableListPrintersOutputBody) Set(val *ListPrintersOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableListPrintersOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableListPrintersOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPrintersOutputBody(val *ListPrintersOutputBody) *NullableListPrintersOutputBody {
	return &NullableListPrintersOutputBody{value: val, isSet: true}
}

func (v NullableListPrintersOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPrintersOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


