/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VoidOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VoidOutputBody{}

// VoidOutputBody struct for VoidOutputBody
type VoidOutputBody struct {
	Zpl string `json:"zpl"`
}

type _VoidOutputBody VoidOutputBody

// NewVoidOutputBody instantiates a new VoidOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoidOutputBody(zpl string) *VoidOutputBody {
	this := VoidOutputBody{}
	this.Zpl = zpl
	return &this
}

// NewVoidOutputBodyWithDefaults instantiates a new VoidOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoidOutputBodyWithDefaults() *VoidOutputBody {
	this := VoidOutputBody{}
	return &this
}

// GetZpl returns the Zpl field value
func (o *VoidOutputBody) GetZpl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Zpl
}

// GetZplOk returns a tuple with the Zpl field value
// and a boolean to check if the value has been set.
func (o *VoidOutputBody) GetZplOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zpl, true
}

// SetZpl sets field value
func (o *VoidOutputBody) SetZpl(v string) {
	o.Zpl = v
}

func (o VoidOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VoidOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["zpl"] = o.Zpl
	return toSerialize, nil
}

func (o *VoidOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"zpl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVoidOutputBody := _VoidOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVoidOutputBody)

	if err != nil {
		return err
	}

	*o = VoidOutputBody(varVoidOutputBody)

	return err
}

type NullableVoidOutputBody struct {
	value *VoidOutputBody
	isSet bool
}

func (v NullableVoidOutputBody) Get() *VoidOutputBody {
	return v.value
}

func (v *NullableVoidOutputBody) Set(val *VoidOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableVoidOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableVoidOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoidOutputBody(val *VoidOutputBody) *NullableVoidOutputBody {
	return &NullableVoidOutputBody{value: val, isSet: true}
}

func (v NullableVoidOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoidOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


