/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Barcode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Barcode{}

// Barcode struct for Barcode
type Barcode struct {
	// Largest blur radius the symbol survives; 0 = no margin
	BlurMarginDots int64 `json:"blurMarginDots"`
	Checks []Check `json:"checks"`
	// X-dimension at other print densities, same dot counts
	CrossDpi []DPIVerdict `json:"crossDpi,omitempty"`
	// CODE_128, CODE_39, ITF, QR_CODE, DATA_MATRIX
	Format string `json:"format"`
	// Measured narrow-element width in printer dots (1D only)
	ModuleDots *float64 `json:"moduleDots,omitempty"`
	QuietLeftModules *float64 `json:"quietLeftModules,omitempty"`
	QuietRightModules *float64 `json:"quietRightModules,omitempty"`
	Value string `json:"value"`
	// Physical narrow-element width at the analyzed density
	XDimensionMm *float64 `json:"xDimensionMm,omitempty"`
}

type _Barcode Barcode

// NewBarcode instantiates a new Barcode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBarcode(blurMarginDots int64, checks []Check, format string, value string) *Barcode {
	this := Barcode{}
	this.BlurMarginDots = blurMarginDots
	this.Checks = checks
	this.Format = format
	this.Value = value
	return &this
}

// NewBarcodeWithDefaults instantiates a new Barcode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBarcodeWithDefaults() *Barcode {
	this := Barcode{}
	return &this
}

// GetBlurMarginDots returns the BlurMarginDots field value
func (o *Barcode) GetBlurMarginDots() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.BlurMarginDots
}

// GetBlurMarginDotsOk returns a tuple with the BlurMarginDots field value
// and a boolean to check if the value has been set.
func (o *Barcode) GetBlurMarginDotsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlurMarginDots, true
}

// SetBlurMarginDots sets field value
func (o *Barcode) SetBlurMarginDots(v int64) {
	o.BlurMarginDots = v
}

// GetChecks returns the Checks field value
// If the value is explicit nil, the zero value for []Check will be returned
func (o *Barcode) GetChecks() []Check {
	if o == nil {
		var ret []Check
		return ret
	}

	return o.Checks
}

// GetChecksOk returns a tuple with the Checks field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Barcode) GetChecksOk() ([]Check, bool) {
	if o == nil || IsNil(o.Checks) {
		return nil, false
	}
	return o.Checks, true
}

// SetChecks sets field value
func (o *Barcode) SetChecks(v []Check) {
	o.Checks = v
}

// GetCrossDpi returns the CrossDpi field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Barcode) GetCrossDpi() []DPIVerdict {
	if o == nil {
		var ret []DPIVerdict
		return ret
	}
	return o.CrossDpi
}

// GetCrossDpiOk returns a tuple with the CrossDpi field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Barcode) GetCrossDpiOk() ([]DPIVerdict, bool) {
	if o == nil || IsNil(o.CrossDpi) {
		return nil, false
	}
	return o.CrossDpi, true
}

// HasCrossDpi returns a boolean if a field has been set.
func (o *Barcode) HasCrossDpi() bool {
	if o != nil && !IsNil(o.CrossDpi) {
		return true
	}

	return false
}

// SetCrossDpi gets a reference to the given []DPIVerdict and assigns it to the CrossDpi field.
func (o *Barcode) SetCrossDpi(v []DPIVerdict) {
	o.CrossDpi = v
}

// GetFormat returns the Format field value
func (o *Barcode) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *Barcode) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *Barcode) SetFormat(v string) {
	o.Format = v
}

// GetModuleDots returns the ModuleDots field value if set, zero value otherwise.
func (o *Barcode) GetModuleDots() float64 {
	if o == nil || IsNil(o.ModuleDots) {
		var ret float64
		return ret
	}
	return *o.ModuleDots
}

// GetModuleDotsOk returns a tuple with the ModuleDots field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Barcode) GetModuleDotsOk() (*float64, bool) {
	if o == nil || IsNil(o.ModuleDots) {
		return nil, false
	}
	return o.ModuleDots, true
}

// HasModuleDots returns a boolean if a field has been set.
func (o *Barcode) HasModuleDots() bool {
	if o != nil && !IsNil(o.ModuleDots) {
		return true
	}

	return false
}

// SetModuleDots gets a reference to the given float64 and assigns it to the ModuleDots field.
func (o *Barcode) SetModuleDots(v float64) {
	o.ModuleDots = &v
}

// GetQuietLeftModules returns the QuietLeftModules field value if set, zero value otherwise.
func (o *Barcode) GetQuietLeftModules() float64 {
	if o == nil || IsNil(o.QuietLeftModules) {
		var ret float64
		return ret
	}
	return *o.QuietLeftModules
}

// GetQuietLeftModulesOk returns a tuple with the QuietLeftModules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Barcode) GetQuietLeftModulesOk() (*float64, bool) {
	if o == nil || IsNil(o.QuietLeftModules) {
		return nil, false
	}
	return o.QuietLeftModules, true
}

// HasQuietLeftModules returns a boolean if a field has been set.
func (o *Barcode) HasQuietLeftModules() bool {
	if o != nil && !IsNil(o.QuietLeftModules) {
		return true
	}

	return false
}

// SetQuietLeftModules gets a reference to the given float64 and assigns it to the QuietLeftModules field.
func (o *Barcode) SetQuietLeftModules(v float64) {
	o.QuietLeftModules = &v
}

// GetQuietRightModules returns the QuietRightModules field value if set, zero value otherwise.
func (o *Barcode) GetQuietRightModules() float64 {
	if o == nil || IsNil(o.QuietRightModules) {
		var ret float64
		return ret
	}
	return *o.QuietRightModules
}

// GetQuietRightModulesOk returns a tuple with the QuietRightModules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Barcode) GetQuietRightModulesOk() (*float64, bool) {
	if o == nil || IsNil(o.QuietRightModules) {
		return nil, false
	}
	return o.QuietRightModules, true
}

// HasQuietRightModules returns a boolean if a field has been set.
func (o *Barcode) HasQuietRightModules() bool {
	if o != nil && !IsNil(o.QuietRightModules) {
		return true
	}

	return false
}

// SetQuietRightModules gets a reference to the given float64 and assigns it to the QuietRightModules field.
func (o *Barcode) SetQuietRightModules(v float64) {
	o.QuietRightModules = &v
}

// GetValue returns the Value field value
func (o *Barcode) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *Barcode) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *Barcode) SetValue(v string) {
	o.Value = v
}

// GetXDimensionMm returns the XDimensionMm field value if set, zero value otherwise.
func (o *Barcode) GetXDimensionMm() float64 {
	if o == nil || IsNil(o.XDimensionMm) {
		var ret float64
		return ret
	}
	return *o.XDimensionMm
}

// GetXDimensionMmOk returns a tuple with the XDimensionMm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Barcode) GetXDimensionMmOk() (*float64, bool) {
	if o == nil || IsNil(o.XDimensionMm) {
		return nil, false
	}
	return o.XDimensionMm, true
}

// HasXDimensionMm returns a boolean if a field has been set.
func (o *Barcode) HasXDimensionMm() bool {
	if o != nil && !IsNil(o.XDimensionMm) {
		return true
	}

	return false
}

// SetXDimensionMm gets a reference to the given float64 and assigns it to the XDimensionMm field.
func (o *Barcode) SetXDimensionMm(v float64) {
	o.XDimensionMm = &v
}

func (o Barcode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Barcode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["blurMarginDots"] = o.BlurMarginDots
	if o.Checks != nil {
		toSerialize["checks"] = o.Checks
	}
	if o.CrossDpi != nil {
		toSerialize["crossDpi"] = o.CrossDpi
	}
	toSerialize["format"] = o.Format
	if !IsNil(o.ModuleDots) {
		toSerialize["moduleDots"] = o.ModuleDots
	}
	if !IsNil(o.QuietLeftModules) {
		toSerialize["quietLeftModules"] = o.QuietLeftModules
	}
	if !IsNil(o.QuietRightModules) {
		toSerialize["quietRightModules"] = o.QuietRightModules
	}
	toSerialize["value"] = o.Value
	if !IsNil(o.XDimensionMm) {
		toSerialize["xDimensionMm"] = o.XDimensionMm
	}
	return toSerialize, nil
}

func (o *Barcode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"blurMarginDots",
		"checks",
		"format",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBarcode := _Barcode{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBarcode)

	if err != nil {
		return err
	}

	*o = Barcode(varBarcode)

	return err
}

type NullableBarcode struct {
	value *Barcode
	isSet bool
}

func (v NullableBarcode) Get() *Barcode {
	return v.value
}

func (v *NullableBarcode) Set(val *Barcode) {
	v.value = val
	v.isSet = true
}

func (v NullableBarcode) IsSet() bool {
	return v.isSet
}

func (v *NullableBarcode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBarcode(val *Barcode) *NullableBarcode {
	return &NullableBarcode{value: val, isSet: true}
}

func (v NullableBarcode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBarcode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


