/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreatePrinterInputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePrinterInputBody{}

// CreatePrinterInputBody struct for CreatePrinterInputBody
type CreatePrinterInputBody struct {
	// Who may print to the TCP port; default open. Use token from CI, where the source address is different every run.
	AccessMode *string `json:"accessMode,omitempty"`
	// Mask PII and strip graphics from every captured frame
	Anonymize *bool `json:"anonymize,omitempty"`
	// Print density in dots/mm (152/203/300/600 dpi); default 8
	Dpmm *int64 `json:"dpmm,omitempty"`
	HeightMm *float64 `json:"heightMm,omitempty"`
	Mode *string `json:"mode,omitempty"`
	Name string `json:"name"`
	// Named label size in inches; alternative to widthMm/heightMm
	Preset *string `json:"preset,omitempty"`
	WebhookUrl *string `json:"webhookUrl,omitempty"`
	WidthMm *float64 `json:"widthMm,omitempty"`
}

type _CreatePrinterInputBody CreatePrinterInputBody

// NewCreatePrinterInputBody instantiates a new CreatePrinterInputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePrinterInputBody(name string) *CreatePrinterInputBody {
	this := CreatePrinterInputBody{}
	this.Name = name
	return &this
}

// NewCreatePrinterInputBodyWithDefaults instantiates a new CreatePrinterInputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePrinterInputBodyWithDefaults() *CreatePrinterInputBody {
	this := CreatePrinterInputBody{}
	return &this
}

// GetAccessMode returns the AccessMode field value if set, zero value otherwise.
func (o *CreatePrinterInputBody) GetAccessMode() string {
	if o == nil || IsNil(o.AccessMode) {
		var ret string
		return ret
	}
	return *o.AccessMode
}

// GetAccessModeOk returns a tuple with the AccessMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePrinterInputBody) GetAccessModeOk() (*string, bool) {
	if o == nil || IsNil(o.AccessMode) {
		return nil, false
	}
	return o.AccessMode, true
}

// HasAccessMode returns a boolean if a field has been set.
func (o *CreatePrinterInputBody) HasAccessMode() bool {
	if o != nil && !IsNil(o.AccessMode) {
		return true
	}

	return false
}

// SetAccessMode gets a reference to the given string and assigns it to the AccessMode field.
func (o *CreatePrinterInputBody) SetAccessMode(v string) {
	o.AccessMode = &v
}

// GetAnonymize returns the Anonymize field value if set, zero value otherwise.
func (o *CreatePrinterInputBody) GetAnonymize() bool {
	if o == nil || IsNil(o.Anonymize) {
		var ret bool
		return ret
	}
	return *o.Anonymize
}

// GetAnonymizeOk returns a tuple with the Anonymize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePrinterInputBody) GetAnonymizeOk() (*bool, bool) {
	if o == nil || IsNil(o.Anonymize) {
		return nil, false
	}
	return o.Anonymize, true
}

// HasAnonymize returns a boolean if a field has been set.
func (o *CreatePrinterInputBody) HasAnonymize() bool {
	if o != nil && !IsNil(o.Anonymize) {
		return true
	}

	return false
}

// SetAnonymize gets a reference to the given bool and assigns it to the Anonymize field.
func (o *CreatePrinterInputBody) SetAnonymize(v bool) {
	o.Anonymize = &v
}

// GetDpmm returns the Dpmm field value if set, zero value otherwise.
func (o *CreatePrinterInputBody) GetDpmm() int64 {
	if o == nil || IsNil(o.Dpmm) {
		var ret int64
		return ret
	}
	return *o.Dpmm
}

// GetDpmmOk returns a tuple with the Dpmm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePrinterInputBody) GetDpmmOk() (*int64, bool) {
	if o == nil || IsNil(o.Dpmm) {
		return nil, false
	}
	return o.Dpmm, true
}

// HasDpmm returns a boolean if a field has been set.
func (o *CreatePrinterInputBody) HasDpmm() bool {
	if o != nil && !IsNil(o.Dpmm) {
		return true
	}

	return false
}

// SetDpmm gets a reference to the given int64 and assigns it to the Dpmm field.
func (o *CreatePrinterInputBody) SetDpmm(v int64) {
	o.Dpmm = &v
}

// GetHeightMm returns the HeightMm field value if set, zero value otherwise.
func (o *CreatePrinterInputBody) GetHeightMm() float64 {
	if o == nil || IsNil(o.HeightMm) {
		var ret float64
		return ret
	}
	return *o.HeightMm
}

// GetHeightMmOk returns a tuple with the HeightMm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePrinterInputBody) GetHeightMmOk() (*float64, bool) {
	if o == nil || IsNil(o.HeightMm) {
		return nil, false
	}
	return o.HeightMm, true
}

// HasHeightMm returns a boolean if a field has been set.
func (o *CreatePrinterInputBody) HasHeightMm() bool {
	if o != nil && !IsNil(o.HeightMm) {
		return true
	}

	return false
}

// SetHeightMm gets a reference to the given float64 and assigns it to the HeightMm field.
func (o *CreatePrinterInputBody) SetHeightMm(v float64) {
	o.HeightMm = &v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *CreatePrinterInputBody) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePrinterInputBody) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *CreatePrinterInputBody) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *CreatePrinterInputBody) SetMode(v string) {
	o.Mode = &v
}

// GetName returns the Name field value
func (o *CreatePrinterInputBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreatePrinterInputBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreatePrinterInputBody) SetName(v string) {
	o.Name = v
}

// GetPreset returns the Preset field value if set, zero value otherwise.
func (o *CreatePrinterInputBody) GetPreset() string {
	if o == nil || IsNil(o.Preset) {
		var ret string
		return ret
	}
	return *o.Preset
}

// GetPresetOk returns a tuple with the Preset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePrinterInputBody) GetPresetOk() (*string, bool) {
	if o == nil || IsNil(o.Preset) {
		return nil, false
	}
	return o.Preset, true
}

// HasPreset returns a boolean if a field has been set.
func (o *CreatePrinterInputBody) HasPreset() bool {
	if o != nil && !IsNil(o.Preset) {
		return true
	}

	return false
}

// SetPreset gets a reference to the given string and assigns it to the Preset field.
func (o *CreatePrinterInputBody) SetPreset(v string) {
	o.Preset = &v
}

// GetWebhookUrl returns the WebhookUrl field value if set, zero value otherwise.
func (o *CreatePrinterInputBody) GetWebhookUrl() string {
	if o == nil || IsNil(o.WebhookUrl) {
		var ret string
		return ret
	}
	return *o.WebhookUrl
}

// GetWebhookUrlOk returns a tuple with the WebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePrinterInputBody) GetWebhookUrlOk() (*string, bool) {
	if o == nil || IsNil(o.WebhookUrl) {
		return nil, false
	}
	return o.WebhookUrl, true
}

// HasWebhookUrl returns a boolean if a field has been set.
func (o *CreatePrinterInputBody) HasWebhookUrl() bool {
	if o != nil && !IsNil(o.WebhookUrl) {
		return true
	}

	return false
}

// SetWebhookUrl gets a reference to the given string and assigns it to the WebhookUrl field.
func (o *CreatePrinterInputBody) SetWebhookUrl(v string) {
	o.WebhookUrl = &v
}

// GetWidthMm returns the WidthMm field value if set, zero value otherwise.
func (o *CreatePrinterInputBody) GetWidthMm() float64 {
	if o == nil || IsNil(o.WidthMm) {
		var ret float64
		return ret
	}
	return *o.WidthMm
}

// GetWidthMmOk returns a tuple with the WidthMm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePrinterInputBody) GetWidthMmOk() (*float64, bool) {
	if o == nil || IsNil(o.WidthMm) {
		return nil, false
	}
	return o.WidthMm, true
}

// HasWidthMm returns a boolean if a field has been set.
func (o *CreatePrinterInputBody) HasWidthMm() bool {
	if o != nil && !IsNil(o.WidthMm) {
		return true
	}

	return false
}

// SetWidthMm gets a reference to the given float64 and assigns it to the WidthMm field.
func (o *CreatePrinterInputBody) SetWidthMm(v float64) {
	o.WidthMm = &v
}

func (o CreatePrinterInputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePrinterInputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessMode) {
		toSerialize["accessMode"] = o.AccessMode
	}
	if !IsNil(o.Anonymize) {
		toSerialize["anonymize"] = o.Anonymize
	}
	if !IsNil(o.Dpmm) {
		toSerialize["dpmm"] = o.Dpmm
	}
	if !IsNil(o.HeightMm) {
		toSerialize["heightMm"] = o.HeightMm
	}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Preset) {
		toSerialize["preset"] = o.Preset
	}
	if !IsNil(o.WebhookUrl) {
		toSerialize["webhookUrl"] = o.WebhookUrl
	}
	if !IsNil(o.WidthMm) {
		toSerialize["widthMm"] = o.WidthMm
	}
	return toSerialize, nil
}

func (o *CreatePrinterInputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePrinterInputBody := _CreatePrinterInputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePrinterInputBody)

	if err != nil {
		return err
	}

	*o = CreatePrinterInputBody(varCreatePrinterInputBody)

	return err
}

type NullableCreatePrinterInputBody struct {
	value *CreatePrinterInputBody
	isSet bool
}

func (v NullableCreatePrinterInputBody) Get() *CreatePrinterInputBody {
	return v.value
}

func (v *NullableCreatePrinterInputBody) Set(val *CreatePrinterInputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePrinterInputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePrinterInputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePrinterInputBody(val *CreatePrinterInputBody) *NullableCreatePrinterInputBody {
	return &NullableCreatePrinterInputBody{value: val, isSet: true}
}

func (v NullableCreatePrinterInputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePrinterInputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


