/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HtmlOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HtmlOutputBody{}

// HtmlOutputBody struct for HtmlOutputBody
type HtmlOutputBody struct {
	HeightPx int64 `json:"heightPx"`
	WidthPx int64 `json:"widthPx"`
	Zpl string `json:"zpl"`
}

type _HtmlOutputBody HtmlOutputBody

// NewHtmlOutputBody instantiates a new HtmlOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHtmlOutputBody(heightPx int64, widthPx int64, zpl string) *HtmlOutputBody {
	this := HtmlOutputBody{}
	this.HeightPx = heightPx
	this.WidthPx = widthPx
	this.Zpl = zpl
	return &this
}

// NewHtmlOutputBodyWithDefaults instantiates a new HtmlOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHtmlOutputBodyWithDefaults() *HtmlOutputBody {
	this := HtmlOutputBody{}
	return &this
}

// GetHeightPx returns the HeightPx field value
func (o *HtmlOutputBody) GetHeightPx() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.HeightPx
}

// GetHeightPxOk returns a tuple with the HeightPx field value
// and a boolean to check if the value has been set.
func (o *HtmlOutputBody) GetHeightPxOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HeightPx, true
}

// SetHeightPx sets field value
func (o *HtmlOutputBody) SetHeightPx(v int64) {
	o.HeightPx = v
}

// GetWidthPx returns the WidthPx field value
func (o *HtmlOutputBody) GetWidthPx() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.WidthPx
}

// GetWidthPxOk returns a tuple with the WidthPx field value
// and a boolean to check if the value has been set.
func (o *HtmlOutputBody) GetWidthPxOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WidthPx, true
}

// SetWidthPx sets field value
func (o *HtmlOutputBody) SetWidthPx(v int64) {
	o.WidthPx = v
}

// GetZpl returns the Zpl field value
func (o *HtmlOutputBody) GetZpl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Zpl
}

// GetZplOk returns a tuple with the Zpl field value
// and a boolean to check if the value has been set.
func (o *HtmlOutputBody) GetZplOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zpl, true
}

// SetZpl sets field value
func (o *HtmlOutputBody) SetZpl(v string) {
	o.Zpl = v
}

func (o HtmlOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HtmlOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["heightPx"] = o.HeightPx
	toSerialize["widthPx"] = o.WidthPx
	toSerialize["zpl"] = o.Zpl
	return toSerialize, nil
}

func (o *HtmlOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"heightPx",
		"widthPx",
		"zpl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHtmlOutputBody := _HtmlOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHtmlOutputBody)

	if err != nil {
		return err
	}

	*o = HtmlOutputBody(varHtmlOutputBody)

	return err
}

type NullableHtmlOutputBody struct {
	value *HtmlOutputBody
	isSet bool
}

func (v NullableHtmlOutputBody) Get() *HtmlOutputBody {
	return v.value
}

func (v *NullableHtmlOutputBody) Set(val *HtmlOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableHtmlOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableHtmlOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHtmlOutputBody(val *HtmlOutputBody) *NullableHtmlOutputBody {
	return &NullableHtmlOutputBody{value: val, isSet: true}
}

func (v NullableHtmlOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHtmlOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


