/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ComposeOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComposeOutputBody{}

// ComposeOutputBody struct for ComposeOutputBody
type ComposeOutputBody struct {
	// Rendered previews when preview=true
	Labels []RenderedLabel `json:"labels,omitempty"`
	Warnings []string `json:"warnings"`
	Zpl string `json:"zpl"`
}

type _ComposeOutputBody ComposeOutputBody

// NewComposeOutputBody instantiates a new ComposeOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComposeOutputBody(warnings []string, zpl string) *ComposeOutputBody {
	this := ComposeOutputBody{}
	this.Warnings = warnings
	this.Zpl = zpl
	return &this
}

// NewComposeOutputBodyWithDefaults instantiates a new ComposeOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComposeOutputBodyWithDefaults() *ComposeOutputBody {
	this := ComposeOutputBody{}
	return &this
}

// GetLabels returns the Labels field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ComposeOutputBody) GetLabels() []RenderedLabel {
	if o == nil {
		var ret []RenderedLabel
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ComposeOutputBody) GetLabelsOk() ([]RenderedLabel, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ComposeOutputBody) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []RenderedLabel and assigns it to the Labels field.
func (o *ComposeOutputBody) SetLabels(v []RenderedLabel) {
	o.Labels = v
}

// GetWarnings returns the Warnings field value
// If the value is explicit nil, the zero value for []string will be returned
func (o *ComposeOutputBody) GetWarnings() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ComposeOutputBody) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// SetWarnings sets field value
func (o *ComposeOutputBody) SetWarnings(v []string) {
	o.Warnings = v
}

// GetZpl returns the Zpl field value
func (o *ComposeOutputBody) GetZpl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Zpl
}

// GetZplOk returns a tuple with the Zpl field value
// and a boolean to check if the value has been set.
func (o *ComposeOutputBody) GetZplOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zpl, true
}

// SetZpl sets field value
func (o *ComposeOutputBody) SetZpl(v string) {
	o.Zpl = v
}

func (o ComposeOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComposeOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Labels != nil {
		toSerialize["labels"] = o.Labels
	}
	if o.Warnings != nil {
		toSerialize["warnings"] = o.Warnings
	}
	toSerialize["zpl"] = o.Zpl
	return toSerialize, nil
}

func (o *ComposeOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"warnings",
		"zpl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varComposeOutputBody := _ComposeOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varComposeOutputBody)

	if err != nil {
		return err
	}

	*o = ComposeOutputBody(varComposeOutputBody)

	return err
}

type NullableComposeOutputBody struct {
	value *ComposeOutputBody
	isSet bool
}

func (v NullableComposeOutputBody) Get() *ComposeOutputBody {
	return v.value
}

func (v *NullableComposeOutputBody) Set(val *ComposeOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableComposeOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableComposeOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComposeOutputBody(val *ComposeOutputBody) *NullableComposeOutputBody {
	return &NullableComposeOutputBody{value: val, isSet: true}
}

func (v NullableComposeOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComposeOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


