/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StatusSnapshot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatusSnapshot{}

// StatusSnapshot struct for StatusSnapshot
type StatusSnapshot struct {
	Faults Faults `json:"faults"`
	FormatsInBuffer int64 `json:"formatsInBuffer"`
	LabelLengthDots int64 `json:"labelLengthDots"`
	Odometer int64 `json:"odometer"`
	WidthDots int64 `json:"widthDots"`
}

type _StatusSnapshot StatusSnapshot

// NewStatusSnapshot instantiates a new StatusSnapshot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatusSnapshot(faults Faults, formatsInBuffer int64, labelLengthDots int64, odometer int64, widthDots int64) *StatusSnapshot {
	this := StatusSnapshot{}
	this.Faults = faults
	this.FormatsInBuffer = formatsInBuffer
	this.LabelLengthDots = labelLengthDots
	this.Odometer = odometer
	this.WidthDots = widthDots
	return &this
}

// NewStatusSnapshotWithDefaults instantiates a new StatusSnapshot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatusSnapshotWithDefaults() *StatusSnapshot {
	this := StatusSnapshot{}
	return &this
}

// GetFaults returns the Faults field value
func (o *StatusSnapshot) GetFaults() Faults {
	if o == nil {
		var ret Faults
		return ret
	}

	return o.Faults
}

// GetFaultsOk returns a tuple with the Faults field value
// and a boolean to check if the value has been set.
func (o *StatusSnapshot) GetFaultsOk() (*Faults, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Faults, true
}

// SetFaults sets field value
func (o *StatusSnapshot) SetFaults(v Faults) {
	o.Faults = v
}

// GetFormatsInBuffer returns the FormatsInBuffer field value
func (o *StatusSnapshot) GetFormatsInBuffer() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.FormatsInBuffer
}

// GetFormatsInBufferOk returns a tuple with the FormatsInBuffer field value
// and a boolean to check if the value has been set.
func (o *StatusSnapshot) GetFormatsInBufferOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FormatsInBuffer, true
}

// SetFormatsInBuffer sets field value
func (o *StatusSnapshot) SetFormatsInBuffer(v int64) {
	o.FormatsInBuffer = v
}

// GetLabelLengthDots returns the LabelLengthDots field value
func (o *StatusSnapshot) GetLabelLengthDots() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.LabelLengthDots
}

// GetLabelLengthDotsOk returns a tuple with the LabelLengthDots field value
// and a boolean to check if the value has been set.
func (o *StatusSnapshot) GetLabelLengthDotsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LabelLengthDots, true
}

// SetLabelLengthDots sets field value
func (o *StatusSnapshot) SetLabelLengthDots(v int64) {
	o.LabelLengthDots = v
}

// GetOdometer returns the Odometer field value
func (o *StatusSnapshot) GetOdometer() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Odometer
}

// GetOdometerOk returns a tuple with the Odometer field value
// and a boolean to check if the value has been set.
func (o *StatusSnapshot) GetOdometerOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Odometer, true
}

// SetOdometer sets field value
func (o *StatusSnapshot) SetOdometer(v int64) {
	o.Odometer = v
}

// GetWidthDots returns the WidthDots field value
func (o *StatusSnapshot) GetWidthDots() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.WidthDots
}

// GetWidthDotsOk returns a tuple with the WidthDots field value
// and a boolean to check if the value has been set.
func (o *StatusSnapshot) GetWidthDotsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WidthDots, true
}

// SetWidthDots sets field value
func (o *StatusSnapshot) SetWidthDots(v int64) {
	o.WidthDots = v
}

func (o StatusSnapshot) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatusSnapshot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["faults"] = o.Faults
	toSerialize["formatsInBuffer"] = o.FormatsInBuffer
	toSerialize["labelLengthDots"] = o.LabelLengthDots
	toSerialize["odometer"] = o.Odometer
	toSerialize["widthDots"] = o.WidthDots
	return toSerialize, nil
}

func (o *StatusSnapshot) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"faults",
		"formatsInBuffer",
		"labelLengthDots",
		"odometer",
		"widthDots",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStatusSnapshot := _StatusSnapshot{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStatusSnapshot)

	if err != nil {
		return err
	}

	*o = StatusSnapshot(varStatusSnapshot)

	return err
}

type NullableStatusSnapshot struct {
	value *StatusSnapshot
	isSet bool
}

func (v NullableStatusSnapshot) Get() *StatusSnapshot {
	return v.value
}

func (v *NullableStatusSnapshot) Set(val *StatusSnapshot) {
	v.value = val
	v.isSet = true
}

func (v NullableStatusSnapshot) IsSet() bool {
	return v.isSet
}

func (v *NullableStatusSnapshot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatusSnapshot(val *StatusSnapshot) *NullableStatusSnapshot {
	return &NullableStatusSnapshot{value: val, isSet: true}
}

func (v NullableStatusSnapshot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatusSnapshot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


