/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HostStatusOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HostStatusOutputBody{}

// HostStatusOutputBody struct for HostStatusOutputBody
type HostStatusOutputBody struct {
	// Every field with its documented meaning and raw token
	Fields []StatusField `json:"fields"`
	Status HostStatus `json:"status"`
}

type _HostStatusOutputBody HostStatusOutputBody

// NewHostStatusOutputBody instantiates a new HostStatusOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHostStatusOutputBody(fields []StatusField, status HostStatus) *HostStatusOutputBody {
	this := HostStatusOutputBody{}
	this.Fields = fields
	this.Status = status
	return &this
}

// NewHostStatusOutputBodyWithDefaults instantiates a new HostStatusOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHostStatusOutputBodyWithDefaults() *HostStatusOutputBody {
	this := HostStatusOutputBody{}
	return &this
}

// GetFields returns the Fields field value
// If the value is explicit nil, the zero value for []StatusField will be returned
func (o *HostStatusOutputBody) GetFields() []StatusField {
	if o == nil {
		var ret []StatusField
		return ret
	}

	return o.Fields
}

// GetFieldsOk returns a tuple with the Fields field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HostStatusOutputBody) GetFieldsOk() ([]StatusField, bool) {
	if o == nil || IsNil(o.Fields) {
		return nil, false
	}
	return o.Fields, true
}

// SetFields sets field value
func (o *HostStatusOutputBody) SetFields(v []StatusField) {
	o.Fields = v
}

// GetStatus returns the Status field value
func (o *HostStatusOutputBody) GetStatus() HostStatus {
	if o == nil {
		var ret HostStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *HostStatusOutputBody) GetStatusOk() (*HostStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *HostStatusOutputBody) SetStatus(v HostStatus) {
	o.Status = v
}

func (o HostStatusOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HostStatusOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Fields != nil {
		toSerialize["fields"] = o.Fields
	}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *HostStatusOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fields",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHostStatusOutputBody := _HostStatusOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHostStatusOutputBody)

	if err != nil {
		return err
	}

	*o = HostStatusOutputBody(varHostStatusOutputBody)

	return err
}

type NullableHostStatusOutputBody struct {
	value *HostStatusOutputBody
	isSet bool
}

func (v NullableHostStatusOutputBody) Get() *HostStatusOutputBody {
	return v.value
}

func (v *NullableHostStatusOutputBody) Set(val *HostStatusOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableHostStatusOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableHostStatusOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHostStatusOutputBody(val *HostStatusOutputBody) *NullableHostStatusOutputBody {
	return &NullableHostStatusOutputBody{value: val, isSet: true}
}

func (v NullableHostStatusOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHostStatusOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


