/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PrinterBodyTCPStruct type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrinterBodyTCPStruct{}

// PrinterBodyTCPStruct struct for PrinterBodyTCPStruct
type PrinterBodyTCPStruct struct {
	Host string `json:"host"`
	Port int32 `json:"port"`
}

type _PrinterBodyTCPStruct PrinterBodyTCPStruct

// NewPrinterBodyTCPStruct instantiates a new PrinterBodyTCPStruct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrinterBodyTCPStruct(host string, port int32) *PrinterBodyTCPStruct {
	this := PrinterBodyTCPStruct{}
	this.Host = host
	this.Port = port
	return &this
}

// NewPrinterBodyTCPStructWithDefaults instantiates a new PrinterBodyTCPStruct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrinterBodyTCPStructWithDefaults() *PrinterBodyTCPStruct {
	this := PrinterBodyTCPStruct{}
	return &this
}

// GetHost returns the Host field value
func (o *PrinterBodyTCPStruct) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *PrinterBodyTCPStruct) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *PrinterBodyTCPStruct) SetHost(v string) {
	o.Host = v
}

// GetPort returns the Port field value
func (o *PrinterBodyTCPStruct) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *PrinterBodyTCPStruct) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *PrinterBodyTCPStruct) SetPort(v int32) {
	o.Port = v
}

func (o PrinterBodyTCPStruct) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrinterBodyTCPStruct) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["host"] = o.Host
	toSerialize["port"] = o.Port
	return toSerialize, nil
}

func (o *PrinterBodyTCPStruct) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"host",
		"port",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrinterBodyTCPStruct := _PrinterBodyTCPStruct{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPrinterBodyTCPStruct)

	if err != nil {
		return err
	}

	*o = PrinterBodyTCPStruct(varPrinterBodyTCPStruct)

	return err
}

type NullablePrinterBodyTCPStruct struct {
	value *PrinterBodyTCPStruct
	isSet bool
}

func (v NullablePrinterBodyTCPStruct) Get() *PrinterBodyTCPStruct {
	return v.value
}

func (v *NullablePrinterBodyTCPStruct) Set(val *PrinterBodyTCPStruct) {
	v.value = val
	v.isSet = true
}

func (v NullablePrinterBodyTCPStruct) IsSet() bool {
	return v.isSet
}

func (v *NullablePrinterBodyTCPStruct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrinterBodyTCPStruct(val *PrinterBodyTCPStruct) *NullablePrinterBodyTCPStruct {
	return &NullablePrinterBodyTCPStruct{value: val, isSet: true}
}

func (v NullablePrinterBodyTCPStruct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrinterBodyTCPStruct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


