/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StampOutputBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StampOutputBody{}

// StampOutputBody struct for StampOutputBody
type StampOutputBody struct {
	Zpl string `json:"zpl"`
}

type _StampOutputBody StampOutputBody

// NewStampOutputBody instantiates a new StampOutputBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStampOutputBody(zpl string) *StampOutputBody {
	this := StampOutputBody{}
	this.Zpl = zpl
	return &this
}

// NewStampOutputBodyWithDefaults instantiates a new StampOutputBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStampOutputBodyWithDefaults() *StampOutputBody {
	this := StampOutputBody{}
	return &this
}

// GetZpl returns the Zpl field value
func (o *StampOutputBody) GetZpl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Zpl
}

// GetZplOk returns a tuple with the Zpl field value
// and a boolean to check if the value has been set.
func (o *StampOutputBody) GetZplOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Zpl, true
}

// SetZpl sets field value
func (o *StampOutputBody) SetZpl(v string) {
	o.Zpl = v
}

func (o StampOutputBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StampOutputBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["zpl"] = o.Zpl
	return toSerialize, nil
}

func (o *StampOutputBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"zpl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStampOutputBody := _StampOutputBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStampOutputBody)

	if err != nil {
		return err
	}

	*o = StampOutputBody(varStampOutputBody)

	return err
}

type NullableStampOutputBody struct {
	value *StampOutputBody
	isSet bool
}

func (v NullableStampOutputBody) Get() *StampOutputBody {
	return v.value
}

func (v *NullableStampOutputBody) Set(val *StampOutputBody) {
	v.value = val
	v.isSet = true
}

func (v NullableStampOutputBody) IsSet() bool {
	return v.isSet
}

func (v *NullableStampOutputBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStampOutputBody(val *StampOutputBody) *NullableStampOutputBody {
	return &NullableStampOutputBody{value: val, isSet: true}
}

func (v NullableStampOutputBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStampOutputBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


