/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Finding type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Finding{}

// Finding struct for Finding
type Finding struct {
	Code string `json:"code"`
	// 1-based label index; 0 = whole stream
	Label int64 `json:"label"`
	Message string `json:"message"`
	Severity string `json:"severity"`
}

type _Finding Finding

// NewFinding instantiates a new Finding object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFinding(code string, label int64, message string, severity string) *Finding {
	this := Finding{}
	this.Code = code
	this.Label = label
	this.Message = message
	this.Severity = severity
	return &this
}

// NewFindingWithDefaults instantiates a new Finding object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindingWithDefaults() *Finding {
	this := Finding{}
	return &this
}

// GetCode returns the Code field value
func (o *Finding) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *Finding) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *Finding) SetCode(v string) {
	o.Code = v
}

// GetLabel returns the Label field value
func (o *Finding) GetLabel() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *Finding) GetLabelOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *Finding) SetLabel(v int64) {
	o.Label = v
}

// GetMessage returns the Message field value
func (o *Finding) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *Finding) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *Finding) SetMessage(v string) {
	o.Message = v
}

// GetSeverity returns the Severity field value
func (o *Finding) GetSeverity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *Finding) GetSeverityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *Finding) SetSeverity(v string) {
	o.Severity = v
}

func (o Finding) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Finding) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["label"] = o.Label
	toSerialize["message"] = o.Message
	toSerialize["severity"] = o.Severity
	return toSerialize, nil
}

func (o *Finding) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"label",
		"message",
		"severity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFinding := _Finding{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFinding)

	if err != nil {
		return err
	}

	*o = Finding(varFinding)

	return err
}

type NullableFinding struct {
	value *Finding
	isSet bool
}

func (v NullableFinding) Get() *Finding {
	return v.value
}

func (v *NullableFinding) Set(val *Finding) {
	v.value = val
	v.isSet = true
}

func (v NullableFinding) IsSet() bool {
	return v.isSet
}

func (v *NullableFinding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFinding(val *Finding) *NullableFinding {
	return &NullableFinding{value: val, isSet: true}
}

func (v NullableFinding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFinding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


