/*
Stripy Horse API

Zebra/ZPL developer tools: render ZPL to PNG, convert PDFs and images to print-ready ZPL, and drive hosted virtual Zebra printers for testing. Authenticate with an API key via `Authorization: Bearer sh_live_…` or `X-Api-Key`.

API version: 1.0.0
Contact: ben@stripyhorse.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package stripyhorse

import (
	"encoding/json"
)

// checks if the Faults type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Faults{}

// Faults struct for Faults
type Faults struct {
	HeadUp *bool `json:"headUp,omitempty"`
	OverTemp *bool `json:"overTemp,omitempty"`
	PaperOut *bool `json:"paperOut,omitempty"`
	Paused *bool `json:"paused,omitempty"`
	RibbonOut *bool `json:"ribbonOut,omitempty"`
	UnderTemp *bool `json:"underTemp,omitempty"`
}

// NewFaults instantiates a new Faults object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFaults() *Faults {
	this := Faults{}
	return &this
}

// NewFaultsWithDefaults instantiates a new Faults object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFaultsWithDefaults() *Faults {
	this := Faults{}
	return &this
}

// GetHeadUp returns the HeadUp field value if set, zero value otherwise.
func (o *Faults) GetHeadUp() bool {
	if o == nil || IsNil(o.HeadUp) {
		var ret bool
		return ret
	}
	return *o.HeadUp
}

// GetHeadUpOk returns a tuple with the HeadUp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Faults) GetHeadUpOk() (*bool, bool) {
	if o == nil || IsNil(o.HeadUp) {
		return nil, false
	}
	return o.HeadUp, true
}

// HasHeadUp returns a boolean if a field has been set.
func (o *Faults) HasHeadUp() bool {
	if o != nil && !IsNil(o.HeadUp) {
		return true
	}

	return false
}

// SetHeadUp gets a reference to the given bool and assigns it to the HeadUp field.
func (o *Faults) SetHeadUp(v bool) {
	o.HeadUp = &v
}

// GetOverTemp returns the OverTemp field value if set, zero value otherwise.
func (o *Faults) GetOverTemp() bool {
	if o == nil || IsNil(o.OverTemp) {
		var ret bool
		return ret
	}
	return *o.OverTemp
}

// GetOverTempOk returns a tuple with the OverTemp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Faults) GetOverTempOk() (*bool, bool) {
	if o == nil || IsNil(o.OverTemp) {
		return nil, false
	}
	return o.OverTemp, true
}

// HasOverTemp returns a boolean if a field has been set.
func (o *Faults) HasOverTemp() bool {
	if o != nil && !IsNil(o.OverTemp) {
		return true
	}

	return false
}

// SetOverTemp gets a reference to the given bool and assigns it to the OverTemp field.
func (o *Faults) SetOverTemp(v bool) {
	o.OverTemp = &v
}

// GetPaperOut returns the PaperOut field value if set, zero value otherwise.
func (o *Faults) GetPaperOut() bool {
	if o == nil || IsNil(o.PaperOut) {
		var ret bool
		return ret
	}
	return *o.PaperOut
}

// GetPaperOutOk returns a tuple with the PaperOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Faults) GetPaperOutOk() (*bool, bool) {
	if o == nil || IsNil(o.PaperOut) {
		return nil, false
	}
	return o.PaperOut, true
}

// HasPaperOut returns a boolean if a field has been set.
func (o *Faults) HasPaperOut() bool {
	if o != nil && !IsNil(o.PaperOut) {
		return true
	}

	return false
}

// SetPaperOut gets a reference to the given bool and assigns it to the PaperOut field.
func (o *Faults) SetPaperOut(v bool) {
	o.PaperOut = &v
}

// GetPaused returns the Paused field value if set, zero value otherwise.
func (o *Faults) GetPaused() bool {
	if o == nil || IsNil(o.Paused) {
		var ret bool
		return ret
	}
	return *o.Paused
}

// GetPausedOk returns a tuple with the Paused field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Faults) GetPausedOk() (*bool, bool) {
	if o == nil || IsNil(o.Paused) {
		return nil, false
	}
	return o.Paused, true
}

// HasPaused returns a boolean if a field has been set.
func (o *Faults) HasPaused() bool {
	if o != nil && !IsNil(o.Paused) {
		return true
	}

	return false
}

// SetPaused gets a reference to the given bool and assigns it to the Paused field.
func (o *Faults) SetPaused(v bool) {
	o.Paused = &v
}

// GetRibbonOut returns the RibbonOut field value if set, zero value otherwise.
func (o *Faults) GetRibbonOut() bool {
	if o == nil || IsNil(o.RibbonOut) {
		var ret bool
		return ret
	}
	return *o.RibbonOut
}

// GetRibbonOutOk returns a tuple with the RibbonOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Faults) GetRibbonOutOk() (*bool, bool) {
	if o == nil || IsNil(o.RibbonOut) {
		return nil, false
	}
	return o.RibbonOut, true
}

// HasRibbonOut returns a boolean if a field has been set.
func (o *Faults) HasRibbonOut() bool {
	if o != nil && !IsNil(o.RibbonOut) {
		return true
	}

	return false
}

// SetRibbonOut gets a reference to the given bool and assigns it to the RibbonOut field.
func (o *Faults) SetRibbonOut(v bool) {
	o.RibbonOut = &v
}

// GetUnderTemp returns the UnderTemp field value if set, zero value otherwise.
func (o *Faults) GetUnderTemp() bool {
	if o == nil || IsNil(o.UnderTemp) {
		var ret bool
		return ret
	}
	return *o.UnderTemp
}

// GetUnderTempOk returns a tuple with the UnderTemp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Faults) GetUnderTempOk() (*bool, bool) {
	if o == nil || IsNil(o.UnderTemp) {
		return nil, false
	}
	return o.UnderTemp, true
}

// HasUnderTemp returns a boolean if a field has been set.
func (o *Faults) HasUnderTemp() bool {
	if o != nil && !IsNil(o.UnderTemp) {
		return true
	}

	return false
}

// SetUnderTemp gets a reference to the given bool and assigns it to the UnderTemp field.
func (o *Faults) SetUnderTemp(v bool) {
	o.UnderTemp = &v
}

func (o Faults) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Faults) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HeadUp) {
		toSerialize["headUp"] = o.HeadUp
	}
	if !IsNil(o.OverTemp) {
		toSerialize["overTemp"] = o.OverTemp
	}
	if !IsNil(o.PaperOut) {
		toSerialize["paperOut"] = o.PaperOut
	}
	if !IsNil(o.Paused) {
		toSerialize["paused"] = o.Paused
	}
	if !IsNil(o.RibbonOut) {
		toSerialize["ribbonOut"] = o.RibbonOut
	}
	if !IsNil(o.UnderTemp) {
		toSerialize["underTemp"] = o.UnderTemp
	}
	return toSerialize, nil
}

type NullableFaults struct {
	value *Faults
	isSet bool
}

func (v NullableFaults) Get() *Faults {
	return v.value
}

func (v *NullableFaults) Set(val *Faults) {
	v.value = val
	v.isSet = true
}

func (v NullableFaults) IsSet() bool {
	return v.isSet
}

func (v *NullableFaults) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFaults(val *Faults) *NullableFaults {
	return &NullableFaults{value: val, isSet: true}
}

func (v NullableFaults) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFaults) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


